import type { Event } from '@/lib/types';

export const events: Event[] = [
  {
    id: 'caaeyc-2026',
    title: 'CAAEYC Annual Conference & Expo 2026',
    organization: 'California Association for the Education of Young Children',
    date: '2026-03-14',
    endDate: '2026-03-16',
    location: 'Pasadena Convention Center, Pasadena, CA',
    audience: 'Early childhood educators, directors, and administrators across California',
    objective: 'Showcase early education solutions with a full booth presence, distribute branded materials, and generate leads among ECE professionals',
    company: 'WELS',
    presence: 'Full 10x10 booth with tablecloth, banners, and swag distribution',
    status: 'archived',
    progress: 65,
    coverGradient: 'from-violet-500 to-purple-700',
    notes: 'Booth #412 confirmed. Need to finalize swag bag items and ensure banner prints arrive by Feb 28. Hotel block closes Feb 1.',
    tags: ['early-education', 'california', 'expo', 'booth', 'spring'],
    links: [
      { label: 'Conference Website', url: 'https://www.caaeyc.org/conference' },
      { label: 'Booth Registration', url: 'https://www.caaeyc.org/exhibitors' },
      { label: 'Hotel Block', url: 'https://marriott.com/lax' },
    ],
    contacts: [
      { name: 'Maria Santos', role: 'Event Coordinator', email: 'msantos@caaeyc.org' },
      { name: 'James Thornton', role: 'WELS Account Manager', email: 'jthornton@wels.com' },
      { name: 'Linda Park', role: 'Print Vendor Contact', email: 'linda@printpro.com' },
    ],
    deadlines: [
      { id: 'dl-c1', title: 'Banner design finalized', date: '2026-02-10', type: 'design', done: true },
      { id: 'dl-c2', title: 'Tablecloth artwork approved', date: '2026-02-14', type: 'review', done: true },
      { id: 'dl-c3', title: 'All print files to vendor', date: '2026-02-28', type: 'print', done: false },
      { id: 'dl-c4', title: 'Swag shipped to Pasadena hotel', date: '2026-03-08', type: 'shipping', done: false },
      { id: 'dl-c5', title: 'CAAEYC Conference', date: '2026-03-14', type: 'conference', done: false },
      { id: 'dl-c6', title: 'Post-event asset archive', date: '2026-03-20', type: 'other', done: false },
    ],
    assets: [
      {
        id: 'a-c1',
        title: '10ft Backdrop Banner',
        type: 'banner',
        previewColor: 'bg-violet-500',
        aspectRatio: '10/3',
        status: 'approved',
        notes: 'Horizontal banner for back of booth wall',
        tags: ['booth', 'print', 'banner'],
        mapPosition: { x: 80, y: 60 },
      },
      {
        id: 'a-c2',
        title: 'Pull-Up Retractable Banner',
        type: 'banner',
        previewColor: 'bg-purple-600',
        aspectRatio: '1/3',
        status: 'approved',
        notes: 'Tall vertical pull-up for booth entrance',
        tags: ['booth', 'print'],
        mapPosition: { x: 300, y: 80 },
      },
      {
        id: 'a-c3',
        title: 'Booth Tablecloth',
        type: 'tablecloth',
        previewColor: 'bg-indigo-500',
        aspectRatio: '2/1',
        status: 'approved',
        notes: '6ft table throw with logo front and center',
        tags: ['booth', 'print', 'table'],
        mapPosition: { x: 500, y: 200 },
      },
      {
        id: 'a-c4',
        title: 'Conference Landing Page',
        type: 'landing',
        previewColor: 'bg-violet-400',
        aspectRatio: '16/9',
        status: 'delivered',
        externalUrl: 'https://wels.com/caaeyc2026',
        notes: 'Landing page for QR scan from booth materials',
        tags: ['digital', 'web', 'landing'],
        mapPosition: { x: 750, y: 120 },
      },
      {
        id: 'a-c5',
        title: 'QR Code — Landing Page',
        type: 'qr',
        previewColor: 'bg-slate-700',
        aspectRatio: '1/1',
        status: 'delivered',
        notes: 'QR pointing to landing page, used on postcard and tablecloth',
        tags: ['digital', 'qr'],
        mapPosition: { x: 900, y: 300 },
      },
      {
        id: 'a-c6',
        title: 'Postcard Handout',
        type: 'postcard',
        previewColor: 'bg-fuchsia-500',
        aspectRatio: '3/2',
        status: 'in-design',
        notes: '4x6 postcard for booth handout — needs QR and copy finalized',
        tags: ['print', 'postcard', 'handout'],
        mapPosition: { x: 140, y: 350 },
      },
      {
        id: 'a-c7',
        title: 'Social Media — Event Announcement',
        type: 'social',
        previewColor: 'bg-pink-500',
        aspectRatio: '1/1',
        status: 'delivered',
        notes: 'Instagram + Facebook square post announcing attendance',
        tags: ['social', 'digital', 'instagram'],
        mapPosition: { x: 400, y: 420 },
      },
      {
        id: 'a-c8',
        title: 'Swag — Tote Bag Mockup',
        type: 'swag',
        previewColor: 'bg-amber-500',
        aspectRatio: '4/5',
        status: 'review',
        notes: 'Canvas tote with WELS logo — 200 qty',
        tags: ['swag', 'mockup', 'giveaway'],
        mapPosition: { x: 650, y: 480 },
      },
      {
        id: 'a-c9',
        title: 'Company Logo (Conference version)',
        type: 'logo',
        previewColor: 'bg-violet-700',
        aspectRatio: '3/1',
        status: 'approved',
        notes: 'Horizontal lockup for conference use, white and full-color variants',
        tags: ['logo', 'brand'],
        mapPosition: { x: 900, y: 560 },
      },
    ],
  },

  {
    id: 'annual-summit-2026',
    title: 'Annual Summit 2026',
    organization: 'BWELZ National Network',
    date: '2026-04-22',
    endDate: '2026-04-24',
    location: 'Orange County Convention Center, Orlando, FL',
    audience: 'Family childcare providers, network coordinators, and policy advocates',
    objective: 'Reinforce brand presence among network partners, unveil new platform features, and collect feedback from active users',
    company: 'BWELZ',
    presence: 'Sponsored breakout session + 10x20 exhibit hall booth',
    status: 'archived',
    progress: 30,
    coverGradient: 'from-orange-400 to-rose-600',
    notes: 'Breakout session confirmed for April 23 at 2pm. Need slide deck template and speaker bio for agenda. Exhibit hall booth adjacent to main entrance.',
    tags: ['summit', 'florida', 'network', 'booth', 'spring'],
    links: [
      { label: 'Summit Website', url: 'https://bwelz.org/summit2026' },
      { label: 'Speaker Portal', url: 'https://bwelz.org/speakers' },
    ],
    contacts: [
      { name: 'Darnell Brooks', role: 'Summit Director', email: 'dbrooks@bwelz.org' },
      { name: 'Priya Nair', role: 'BWELZ Marketing Lead', email: 'pnair@bwelz.com' },
    ],
    deadlines: [
      { id: 'dl-s1', title: 'Slide deck template designed', date: '2026-03-15', type: 'design', done: false },
      { id: 'dl-s2', title: 'Banner design review', date: '2026-03-28', type: 'review', done: false },
      { id: 'dl-s3', title: 'Print files submitted', date: '2026-04-05', type: 'print', done: false },
      { id: 'dl-s4', title: 'Materials shipped to Orlando', date: '2026-04-15', type: 'shipping', done: false },
      { id: 'dl-s5', title: 'Annual Summit 2026', date: '2026-04-22', type: 'conference', done: false },
    ],
    assets: [
      {
        id: 'a-s1',
        title: 'Booth Backdrop 10x20',
        type: 'banner',
        previewColor: 'bg-orange-500',
        aspectRatio: '20/6',
        status: 'in-design',
        notes: 'Wide-format backdrop for large booth',
        tags: ['booth', 'banner', 'print'],
        mapPosition: { x: 60, y: 80 },
      },
      {
        id: 'a-s2',
        title: 'Breakout Session Slides',
        type: 'pdf',
        previewColor: 'bg-rose-500',
        aspectRatio: '16/9',
        status: 'pending',
        notes: 'Slide template + speaker content for breakout',
        tags: ['slides', 'presentation', 'digital'],
        mapPosition: { x: 350, y: 100 },
      },
      {
        id: 'a-s3',
        title: 'Pull-Up Banner — Feature Announcement',
        type: 'banner',
        previewColor: 'bg-amber-500',
        aspectRatio: '1/3',
        status: 'pending',
        notes: 'Highlight new platform features for summit audience',
        tags: ['banner', 'booth'],
        mapPosition: { x: 600, y: 80 },
      },
      {
        id: 'a-s4',
        title: 'Social — Summit Attendance Post',
        type: 'social',
        previewColor: 'bg-pink-400',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'Pre-event social post for LinkedIn + Instagram',
        tags: ['social', 'digital'],
        mapPosition: { x: 100, y: 350 },
      },
      {
        id: 'a-s5',
        title: 'Postcard — Platform Feature Highlight',
        type: 'postcard',
        previewColor: 'bg-orange-400',
        aspectRatio: '3/2',
        status: 'pending',
        notes: '5x7 postcard showcasing top 3 platform features',
        tags: ['print', 'postcard'],
        mapPosition: { x: 420, y: 380 },
      },
      {
        id: 'a-s6',
        title: 'QR Code — App Download',
        type: 'qr',
        previewColor: 'bg-slate-600',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'QR to app store download page',
        tags: ['qr', 'digital'],
        mapPosition: { x: 700, y: 420 },
      },
      {
        id: 'a-s7',
        title: 'Tablecloth — BWELZ Branded',
        type: 'tablecloth',
        previewColor: 'bg-rose-600',
        aspectRatio: '2/1',
        status: 'pending',
        notes: '6ft stretch tablecloth in brand colors',
        tags: ['booth', 'print', 'table'],
        mapPosition: { x: 900, y: 200 },
      },
    ],
  },

  {
    id: 'smart-start-2026',
    title: 'Smart Start Conference',
    organization: 'Smart Start NC',
    date: '2026-05-08',
    endDate: '2026-05-09',
    location: 'Raleigh Convention Center, Raleigh, NC',
    audience: 'Early childhood coalition members, county partners, funders, and policymakers',
    objective: 'Establish PreK.Club as a trusted platform for NC early childhood networks; generate partnership inquiries',
    company: 'PreK.Club',
    presence: 'Exhibitor table in networking hall',
    status: 'archived',
    progress: 20,
    coverGradient: 'from-emerald-400 to-teal-600',
    notes: 'Table in networking hall (not full booth). Simple setup — tablecloth, signage, and postcard stack. Budget is limited.',
    tags: ['north-carolina', 'early-childhood', 'coalition', 'spring'],
    links: [
      { label: 'Smart Start Conference', url: 'https://smartstart.org/conference' },
    ],
    contacts: [
      { name: 'Tamara Wells', role: 'Conference Chair', email: 'twells@smartstart.org' },
      { name: 'Oscar Reeves', role: 'PreK.Club Partner Lead', email: 'oreeves@prek.club' },
    ],
    deadlines: [
      { id: 'dl-ss1', title: 'Table signage designed', date: '2026-04-10', type: 'design', done: false },
      { id: 'dl-ss2', title: 'Postcard copy approved', date: '2026-04-18', type: 'review', done: false },
      { id: 'dl-ss3', title: 'Print files sent', date: '2026-04-25', type: 'print', done: false },
      { id: 'dl-ss4', title: 'Smart Start Conference', date: '2026-05-08', type: 'conference', done: false },
    ],
    assets: [
      {
        id: 'a-ss1',
        title: 'Table Sign — PreK.Club Intro',
        type: 'banner',
        previewColor: 'bg-emerald-500',
        aspectRatio: '4/3',
        status: 'pending',
        notes: 'Countertop table sign for exhibitor table',
        tags: ['signage', 'print', 'table'],
        mapPosition: { x: 80, y: 100 },
      },
      {
        id: 'a-ss2',
        title: 'Postcard — What is PreK.Club?',
        type: 'postcard',
        previewColor: 'bg-teal-500',
        aspectRatio: '3/2',
        status: 'pending',
        notes: 'Intro postcard with QR code to sign-up page',
        tags: ['print', 'postcard', 'intro'],
        mapPosition: { x: 320, y: 150 },
      },
      {
        id: 'a-ss3',
        title: 'QR Code — Signup Flow',
        type: 'qr',
        previewColor: 'bg-slate-600',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'QR to prek.club/smartstart registration flow',
        tags: ['qr', 'digital'],
        mapPosition: { x: 550, y: 200 },
      },
      {
        id: 'a-ss4',
        title: 'Social — NC Conference Announcement',
        type: 'social',
        previewColor: 'bg-green-500',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'LinkedIn post targeting NC early childhood network',
        tags: ['social', 'digital'],
        mapPosition: { x: 100, y: 400 },
      },
      {
        id: 'a-ss5',
        title: 'Tablecloth — PreK.Club Green',
        type: 'tablecloth',
        previewColor: 'bg-emerald-600',
        aspectRatio: '2/1',
        status: 'pending',
        notes: '6ft table throw in PreK.Club brand green',
        tags: ['booth', 'print'],
        mapPosition: { x: 700, y: 350 },
      },
      {
        id: 'a-ss6',
        title: 'One-pager PDF — Platform Overview',
        type: 'pdf',
        previewColor: 'bg-teal-400',
        aspectRatio: '8.5/11',
        status: 'pending',
        notes: 'Printable one-pager for county coordinators',
        tags: ['pdf', 'print', 'overview'],
        mapPosition: { x: 950, y: 150 },
      },
    ],
  },

  {
    id: 'grow-lead-succeed-2026',
    title: 'FACCM & APPLE - Grow. Lead. Succeed. 2026 Conference',
    organization: 'FACCM, APPLE',
    date: '2026-06-19',
    endDate: '2026-06-20',
    location: 'Loews Sapphire Falls Resort, Orlando, FL',
    audience: 'Site Admins, Leadership, Policy Makers',
    objective: 'Reach out to accredited providers in Florida to present a better way to manage their schools enrollments, payments, and communication with parents',
    company: 'PreK.Club',
    presence: 'Onsite',
    status: 'planning',
    progress: 45,
    coverGradient: 'from-blue-400 to-indigo-600',
    notes: `Primary focus: conference sponsorship visibility, provider outreach, and live product demos for PreK.Club.

Onsite team: Heidy Valdes and Natalia Colleti.
Main hall booth placement — high foot traffic expected.

Live demo station required with tablet/laptop setup.
Demo accounts, QR tracking, and lead capture workflow must be prepared before shipment.

Primary goals:
- Generate qualified provider leads
- Schedule demos
- Increase PreK.Club awareness
- Capture conference content for social media and post-event marketing`,
    tags: ['conference', 'sponsorship', 'prekclub', 'childcare', 'marketing', 'booth', 'demo', 'lead-generation', 'onsite', 'education', 'networking', 'summer'],
    backlog: [
      // SOCIAL
      {
        id: 'bl-g-s1', title: 'LinkedIn Sponsor Post',
        category: 'social', status: 'in-progress', priority: 'high',
        direction: [
          'Premium and SaaS-oriented — clean gradient background',
          'Device mockups with actual PreK.Club UI screenshots',
          'Conference badge/tag element + subtle Orlando/summer vibes',
          '"Proud Sponsor" + "FACCM & APPLE 2026" label',
          'QR or CTA button',
          'UI screens: provider profile, payments, attendance',
        ],
        headline: 'Modern Child Care Management for Growing Programs',
        cta: 'Visit us at FACCM & APPLE 2026',
        missing: ['Real UI screenshots (high-res)', 'Final design file'],
      },
      {
        id: 'bl-g-s2', title: 'Instagram / Facebook Feed Post',
        category: 'social', status: 'in-progress', priority: 'high',
        direction: [
          'Brighter, more colorful — childcare energy, not SaaS-flat',
          'Focus on program growth: providers, teachers, daily operations',
          'Show real product: enrollment dashboard, attendance grid, payments, family communication',
          'Mobile app screens + provider profile UI',
        ],
        headline: 'Enrollment, Payments & Communication — All in One Place',
        cta: 'Visit Us at FACCM & APPLE 2026',
        missing: ['Final design', 'High-res product screenshots', 'Mobile app screens'],
      },
      {
        id: 'bl-g-s3', title: 'IG Story — See You There',
        category: 'social', status: 'in-progress', priority: 'medium',
        direction: [
          'Vertical layout, big CTA',
          'QR at bottom',
          '"Swipe Up" feel even if static',
        ],
        headline: 'See You at FACCM & APPLE 2026',
        notes: 'Subcopy: Live demos • QR signup • Meet the team',
        missing: ['Final design file'],
      },
      {
        id: 'bl-g-s4', title: 'IG Story — Countdown',
        category: 'social', status: 'in-progress', priority: 'medium',
        variants: ['5 days', '3 days', 'Tomorrow'],
        direction: [
          'Animated gradients',
          'Floating UI cards',
          'Subtle dots/shapes from conference design system',
        ],
        headline: "We're heading to Orlando ☀️",
        missing: ['3 variant designs', 'Animation (if motion)'],
      },
      {
        id: 'bl-g-s5', title: 'Post-Event Recap',
        category: 'social', status: 'in-progress', priority: 'medium',
        direction: ['Photo collage — networking, booth moments, QR scans, live demos'],
        headline: 'Thank You FACCM & APPLE 2026',
        missing: ['Conference photos', 'Final design'],
      },
      // DIGITAL
      {
        id: 'bl-g-d1', title: 'Conference Landing Page',
        category: 'digital', status: 'in-progress', priority: 'high',
        missing: [
          '"Meet us at the conference" section',
          'Event countdown widget',
          'Booth location map/info',
          'Live demo CTA block',
          'QR section',
          'FACCM/APPLE sponsor section',
          'UI screenshots: provider profile, payments, attendance, parent app, Google discovery',
        ],
      },
      {
        id: 'bl-g-d2', title: 'Thank-You Page',
        category: 'digital', status: 'in-progress', priority: 'high',
        notes: 'Shown after QR scan or demo form submission.',
        direction: [
          '"Thanks for connecting with PreK.Club! Our team will reach out soon."',
          'Explore how providers use PreK.Club section',
          'Video/demo CTA + social links + schedule a meeting button',
        ],
        missing: ['Page design', 'Video/demo asset'],
      },
      {
        id: 'bl-g-d3', title: 'Demo Booking Form',
        category: 'digital', status: 'in-progress', priority: 'high',
        missing: [
          'Program name field',
          'Role field',
          'Number of children field',
          'Interested features field',
          'Current software field',
          'Preferred demo time field',
        ],
      },
      {
        id: 'bl-g-d4', title: 'QR Experience Flow',
        category: 'digital', status: 'todo', priority: 'medium',
        notes: 'Instead of QR → form directly, build a conversion funnel for better results.',
        direction: [
          '1. Landing hero',
          '2. Quick value props',
          '3. Demo CTA',
          '4. Form',
        ],
        missing: ['Conversion-optimized landing design', 'Flow implementation'],
      },
      // BOOTH
      {
        id: 'bl-g-b1', title: 'Booth Backdrop',
        category: 'booth', status: 'in-progress', priority: 'high',
        direction: [
          'Real UI screenshots + parent app screens + provider dashboards',
          'Tagline system with clear typography hierarchy',
          'Gradient ribbons/waves from postcard design language',
        ],
        headline: 'The Child Care Software to Grow Your Program',
        missing: ['High-res UI screenshot assets', 'Final tagline decision', 'Revised design file'],
      },
      {
        id: 'bl-g-b2', title: 'Tabletop Sign',
        category: 'booth', status: 'in-progress', priority: 'medium',
        notes: 'Quick scan interaction point. 3 benefits max + QR + CTA.',
        direction: [
          'Scan to Explore PreK.Club',
          '✔ Enrollments  ✔ Payments  ✔ Parent Communication',
        ],
        missing: ['QR placement design', 'Final print file'],
      },
      {
        id: 'bl-g-b3', title: 'TV Demo Loop',
        category: 'booth', status: 'in-progress', priority: 'high',
        notes: 'Silent looping video for booth TV. Apple/SaaS style — slow pan, clean transitions, no heavy motion.',
        direction: [
          '1. Logo animation',
          '2. Provider search screen',
          '3. Payments dashboard',
          '4. Parent app',
          '5. Attendance reports',
          '6. Messaging screen',
          '7. "Book a Demo" slide',
          '8. QR code',
        ],
        missing: ['Screen recordings of each UI section', 'Motion design / video file'],
      },
      {
        id: 'bl-g-b4', title: 'Stickers / Swag',
        category: 'booth', status: 'done', priority: 'optional',
        direction: [
          'Mascot stickers',
          '"Play • Learn • Love" mini cards',
          'QR mini cards',
          'Holographic stickers',
          'Die-cut mascot shapes',
        ],
        missing: ['Mascot artwork', 'Vendor selection', 'Print files'],
      },
      // PRINT
      {
        id: 'bl-g-p1', title: 'One-Pager',
        category: 'print', status: 'in-progress', priority: 'high',
        notes: 'Content is ready. Needs layout refinement.',
        direction: [
          'Cleaner feature grouping + more whitespace',
          '"Why Providers Choose PreK.Club" section',
          'Conference CTA block',
          'QR CTA footer',
        ],
        missing: ['Hero → Benefits → Screenshots → Parent Exp → Provider Exp → QR CTA layout', 'Final print file'],
      },
      {
        id: 'bl-g-p2', title: 'Business Card',
        category: 'print', status: 'todo', priority: 'medium',
        direction: ['QR on back', 'Conference-specific CTA on front'],
        headline: 'Meet us at FACCM & APPLE 2026',
        missing: ['Front design', 'Back QR design', 'Print file'],
      },
      // CONTENT
      {
        id: 'bl-g-c1', title: 'Booth Talking Points',
        category: 'content', status: 'done', priority: 'medium',
        direction: [
          'Get found by families on Google',
          'Simplify attendance tracking',
          'Manage payments easily',
          'Improve family communication',
          'Modern provider profiles',
          'Built for growing programs',
        ],
      },
      // SYSTEM
      {
        id: 'bl-g-sys1', title: 'CTA System',
        category: 'system', status: 'done', priority: 'high',
        direction: [
          'Primary: Book a Demo',
          'Secondary: Explore PreK.Club',
          'Event: Visit Us at FACCM & APPLE 2026',
        ],
      },
      {
        id: 'bl-g-sys5', title: 'Lead Collection Workflow',
        category: 'system', status: 'todo', priority: 'high',
        notes: 'Define what happens when someone shows real interest — from first QR scan to demo scheduled.\n\nFlow: QR Scan → Landing Page → Demo / Contact Form → Thank-You Page → CRM / Email Capture → Follow-Up Campaign → Demo Scheduling',
        direction: [
          'Entry points: Booth QR · Demo form · Tabletop QR · Business cards · Social traffic (LinkedIn/Instagram)',
          'Capture fields: Name · Email · Phone · Program Name · Role · # Students · Current Software · Interested Features',
          'Hot Lead: requested demo or meeting',
          'Warm Lead: interested but no immediate action',
          'Partner / Org: networking or collaboration contact',
          'Same day: thank-you email + resource links + demo CTA',
          '2–3 days: personalized follow-up + product walkthrough invitation',
          '1 week: reminder CTA + feature highlights + case study or screenshots',
        ],
        headline: 'Internal Workflow',
        cta: 'During: export leads daily · mark hot leads · assign follow-up owners\nAfter: segment leads · start nurturing · schedule demos · review conversions',
        missing: [
          'CRM or spreadsheet set up for lead capture',
          'Demo form connected to email capture',
          'Follow-up email sequence written and scheduled',
          'Lead owners assigned before conference',
          'Metrics: total leads · demo requests · QR-to-form rate · warm vs hot · follow-up response rate',
        ],
        variants: ['Hot Lead', 'Warm Lead', 'Partner / Org', 'Existing Client'],
      },
      {
        id: 'bl-g-sys4', title: 'Social Campaign Structure',
        category: 'system', status: 'todo', priority: 'high',
        notes: 'Organize what gets published, when, and with what objective across the three conference phases.',
        direction: [
          'PRE-CONFERENCE — Sponsor Announcement: LinkedIn + Facebook + Instagram',
          'PRE-CONFERENCE — "See You There": IG Stories, countdown posts, teaser graphics',
          'PRE-CONFERENCE — Product Highlights: Enrollment · Attendance · Payments · Parent communication',
          'CONFERENCE WEEK — Live Coverage: booth photos, team photos, networking moments, live demos, short videos',
          'CONFERENCE WEEK — Story Coverage: "Visit us today" · "Live demos happening now" · "Come meet the team"',
          'POST-CONFERENCE — Thank You Post: community appreciation and visibility',
          'POST-CONFERENCE — Recap Carousel: booth + demos + networking + team moments',
          'POST-CONFERENCE — Follow-Up CTA: Book a demo · Explore PreK.Club · Schedule a walkthrough',
        ],
        headline: 'Suggested Timeline',
        cta: 'Before: announcement + countdown + features → During: live stories + demos → After: thank-you + recap + follow-up CTA',
        missing: [
          'Content calendar with publish dates',
          'Live coverage assigned to team member',
          'Recap carousel design',
          'Follow-up CTA campaign copy',
          'Metrics baseline: social clicks, story engagement, QR scans, demo requests, traffic source',
        ],
        variants: ['LinkedIn', 'Instagram', 'Facebook'],
      },
      {
        id: 'bl-g-sys3', title: 'QR & Conversion Tracking',
        category: 'system', status: 'todo', priority: 'high',
        notes: 'Define what counts as a real conversion and instrument each QR touchpoint in GA4.\n\nTracking flow: QR Scan → Conference Landing Page → CTA Interaction → Demo Form / Booking → Thank-You Page → GA4 Conversion Recorded',
        direction: [
          'Booth QR — main booth traffic and live demos',
          'Postcard QR — printed material engagement',
          'Tabletop QR — quick interaction during conversations',
          'TV Loop QR — passive booth engagement from screens',
          'GA4 events: conference_qr_visit · demo_form_submit · demo_booking · conference_cta_click',
        ],
        headline: 'Conversion Goals',
        cta: 'Primary: Demo form submitted · Demo booking completed · Contact form submitted\nSecondary: QR scan landing visit · CTA button click · Time on page · Scroll depth · Multiple page views',
        missing: [
          'Most scanned QR — identify best placement',
          'Best performing social platform',
          'Demo conversion rate tracking',
          'Landing page engagement metrics',
          'Conference ROI indicators dashboard',
          'GA4 events instrumented on landing + thank-you page',
        ],
        variants: ['Social Campaign Structure', 'Lead Collection Workflow', 'Booth Experience', 'Post-Event Follow-Up', 'Analytics Dashboard'],
      },
      {
        id: 'bl-g-sys2', title: 'Analytics Setup — UTM Tracking',
        category: 'system', status: 'in-progress', priority: 'high',
        notes: 'Track conference traffic across booth assets, social posts, QR codes, and follow-up campaigns using standardized UTM parameters.\n\nPattern: ?utm_source={source}&utm_medium={medium}&utm_campaign=faccm2026',
        direction: [
          'Booth QR → utm_source=booth&utm_medium=qr',
          'Postcard QR → utm_source=postcard&utm_medium=qr',
          'Tabletop Sign QR → utm_source=tabletop&utm_medium=qr',
          'TV Demo Loop QR → utm_source=tvloop&utm_medium=qr',
          'LinkedIn Post → utm_source=linkedin&utm_medium=social',
          'Instagram Story → utm_source=instagram&utm_medium=story',
          'Follow-Up Email → utm_source=email&utm_medium=followup',
        ],
        missing: [
          'GA4 goals: QR scans, landing page visits, demo form submissions, demo bookings',
          'Social traffic attribution configured',
          'Booth engagement analytics dashboard',
          'All QR codes regenerated with UTM URLs',
        ],
      },
    ],
    links: [
      { label: 'GLS Conference', url: 'https://appleaccreditation.org/conference-2026/' },
      { label: 'Whova Event App', url: 'https://whova.com/web/C%40qggqv92hycv4%40D%40KL1kxnBpd4nAoFm4mxuhJojqBE%3D/' },
    ],
    contacts: [
      { name: 'Joyce Beauchamp', role: 'Digital Marketing & Events Manager — Florida Association for Child Care Management (FACCM)', email: 'jbeauchamp@faccm.org', phone: '954.869.7154 x3001', website: 'faccm.org', group: 'Event / Organization' },
      { name: 'Carlos M. Valdes', role: '', group: 'Internal Team' },
      { name: 'Heidy Valdes', role: '', group: 'Internal Team' },
      { name: 'Abel Ferro', role: '', group: 'Internal Team' },
      { name: 'Natalia Colleti', role: '', group: 'Internal Team' },
    ],
    deadlines: [
      { id: 'dl-g0a', title: 'Conference sponsorship confirmed', date: '2026-05-12', type: 'other', done: true },
      { id: 'dl-g0b', title: 'Event page & registration links reviewed', date: '2026-05-15', type: 'review', done: true },
      { id: 'dl-g0c', title: 'Client brand assets received (logos, brand kit)', date: '2026-05-19', type: 'other', done: true },
      { id: 'dl-g0d', title: 'QR codes generated with UTM tracking', date: '2026-05-22', type: 'design', done: true },
      { id: 'dl-g0e', title: 'SafetyPlug print design approved', date: '2026-05-23', type: 'design', done: true },
      { id: 'dl-g0f', title: 'Postcard 5×7 print design approved', date: '2026-05-25', type: 'design', done: true },
      { id: 'dl-g1',  title: 'Copy & messaging finalized (sponsor announcement, CTA, captions, talking points)', date: '2026-05-28', type: 'design', done: true },
      { id: 'dl-g2',  title: 'Digital assets live (landing page, QR code, booking form, thank-you page, GA4)', date: '2026-05-30', type: 'design', done: false },
      { id: 'dl-g3',  title: 'LinkedIn sponsor post published', date: '2026-05-30', type: 'other', done: false },
      { id: 'dl-g4',  title: 'Print design files ready (backdrop, tabletop sign)', date: '2026-06-01', type: 'design', done: false },
      { id: 'dl-g5',  title: 'Instagram & Facebook pre-event post', date: '2026-06-02', type: 'other', done: false },
      { id: 'dl-g6',  title: 'Print files submitted to vendor', date: '2026-06-03', type: 'print', done: false },
      { id: 'dl-g7',  title: 'Materials shipped to Orlando', date: '2026-06-10', type: 'shipping', done: false },
      { id: 'dl-g8',  title: 'Lead collection workflow & demo accounts ready', date: '2026-06-15', type: 'review', done: false },
      { id: 'dl-g9',  title: 'Final prep check — all systems go', date: '2026-06-17', type: 'review', done: false },
      { id: 'dl-g10', title: 'FACCM & APPLE — Grow. Lead. Succeed. 2026 Conference', date: '2026-06-19', type: 'conference', done: false },
      { id: 'dl-g11', title: 'Post-event recap post + follow-up email sequence sent', date: '2026-06-23', type: 'other', done: false },
    ],
    assets: [
      // ── SOCIAL ──────────────────────────────────────────────
      {
        id: 'a-g-s1', title: 'LinkedIn Sponsor Post',
        type: 'social', category: 'social',
        previewColor: 'bg-blue-600', aspectRatio: '4/5', status: 'review',
        previewUrl: '/prints/grow-lead-succeed-2026/LinkedIn_Sponsor_Post_thumb.png',
        notes: 'PreK.Club is proud to sponsor the 2026 FACCM & APPLE Accreditation Conference in Orlando, FL. 🌴\n\nWe\'re excited to connect with early learning leaders across Florida and share modern tools that help providers simplify enrollment, attendance, payments, and family communication.\n\nStop by to explore live demos, discover new features, and see how PreK.Club helps programs grow with confidence.\n\n📍 Loews Sapphire Falls Resort\n📅 June 19–20, 2026\n\n#FACCM2026 #APPLEAccreditation #PreKClub #EarlyLearning #ChildCare #ChildCareManagement',
        tags: ['social', 'linkedin', 'sponsorship', 'announcement'],
        mapPosition: { x: 55, y: 75 },
      },
      {
        id: 'a-g-s2', title: 'Instagram / Facebook Post',
        type: 'social', category: 'social',
        previewColor: 'bg-blue-400', aspectRatio: '4/5', status: 'review',
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_IGFBFeed_Post_Thumb.png',
        notes: 'We\'re excited to be part of the 2026 FACCM & APPLE Accreditation Conference. 🌱\n\nStop by and discover how PreK.Club helps providers simplify enrollment, communication, and school management — all in one place.\n\n📍 Orlando, FL\n📅 June 19–20\n\nSee you there!',
        tags: ['social', 'instagram', 'facebook', 'announcement'],
        mapPosition: { x: 235, y: 75 },
      },
      {
        id: 'a-g-s3', title: 'Post-Event Recap',
        type: 'social', category: 'social',
        previewColor: 'bg-sky-500', aspectRatio: '3/4', status: 'in-design',
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_PostEventRecap_Thumb.png',
        notes: 'Thank you to everyone who connected with us during the FACCM & APPLE 2026 Conference.\n\nWe loved meeting providers, leaders, and partners committed to strengthening early learning across Florida.\n\nLooking forward to continuing the conversation.',
        tags: ['social', 'recap', 'post-event'],
        mapPosition: { x: 415, y: 75 },
      },

      // ── SOCIAL (stories) ────────────────────────────────────
      {
        id: 'a-g-s6', title: 'IG Story — See You There',
        type: 'social', category: 'social',
        previewColor: 'bg-indigo-500', aspectRatio: '9/16', status: 'review',
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_IGStory_SeeYouThere_Thumb.png',
        notes: 'See you at FACCM & APPLE 2026 👋\n\nVisit the PreK.Club booth for live demos, new tools, and conversations about the future of early learning management.\n\n📍 Loews Sapphire Falls Resort\n📅 June 19–20',
        tags: ['social', 'instagram', 'story', 'promo'],
        mapPosition: { x: 415, y: 215 },
      },
      {
        id: 'a-g-s7', title: 'IG Story — Countdown',
        type: 'social', category: 'social',
        previewColor: 'bg-sky-600', aspectRatio: '9/16', status: 'review',
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_IGStory_Countdown_Thumb.png',
        notes: '3 days until FACCM & APPLE 2026 ✨\n\nWe\'re getting ready for live demos, new connections, and exciting conversations with providers across Florida.\n\nStop by the PreK.Club booth!',
        tags: ['social', 'instagram', 'story', 'countdown'],
        mapPosition: { x: 235, y: 310 },
      },

      // ── DIGITAL ─────────────────────────────────────────────
      {
        id: 'a-g-d1', title: 'Conference Landing Page',
        type: 'landing', category: 'digital',
        previewColor: 'bg-violet-500', aspectRatio: '16/9', status: 'in-design',
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_LandingPage_Thumb.png',
        iframeUrl: 'https://play.prek.club/',
        externalUrl: 'https://play.prek.club/',
        notes: 'Modern tools for early learning providers.\n\nPreK.Club helps programs manage enrollments, payments, communication, and daily operations in one connected platform.\n\nVisit us during FACCM & APPLE 2026.',
        tags: ['digital', 'web', 'landing'],
        mapPosition: { x: 665, y: 75 },
      },
      {
        id: 'a-g-d3', title: 'Demo Booking Form',
        type: 'landing', category: 'digital',
        previewColor: 'bg-indigo-500', aspectRatio: '3/2', status: 'in-design',
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_DemoBookingForm_Thumb.png',
        notes: 'Form for attendees to book a live product demo',
        tags: ['digital', 'form', 'demo'],
        mapPosition: { x: 1025, y: 75 },
      },
      {
        id: 'a-g-d4', title: 'Thank-You Page',
        type: 'landing', category: 'digital',
        previewColor: 'bg-indigo-400', aspectRatio: '5/3', status: 'in-design',
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_ThankYouPage_Thumb.png',
        notes: 'Post-form thank-you page with next steps',
        tags: ['digital', 'web'],
        mapPosition: { x: 665, y: 240 },
      },
      {
        id: 'a-g-d5', title: 'Analytics & Tracking Setup',
        type: 'workflow', category: 'operations',
        previewColor: 'bg-purple-500', aspectRatio: '4/3', status: 'in-design',
        notes: 'UTM PATTERN\n\n?utm_source={source}&utm_medium={medium}&utm_campaign=faccm2026\n\nUTM URLS BY ASSET\n- Booth QR → utm_source=booth&utm_medium=qr\n- Postcard QR → utm_source=postcard&utm_medium=qr\n- Tabletop QR → utm_source=tabletop&utm_medium=qr\n- TV Loop QR → utm_source=tvloop&utm_medium=qr\n- LinkedIn Post → utm_source=linkedin&utm_medium=social\n- Instagram Story → utm_source=instagram&utm_medium=story\n- Follow-Up Email → utm_source=email&utm_medium=followup\n\nGA4 EVENTS\n- conference_qr_visit\n- demo_form_submit\n- demo_booking\n- conference_cta_click\n\nCONVERSION GOALS\n- Demo form submitted\n- Demo booking completed\n- QR scan → landing visit\n- CTA button click',
        tags: ['operations', 'analytics', 'tracking', 'utm', 'ga4'],
        mapPosition: { x: 845, y: 240 },
      },

      // ── BOOTH ────────────────────────────────────────────────
      {
        id: 'a-g-b1', title: 'Booth Backdrop',
        type: 'banner', category: 'booth',
        previewColor: 'bg-emerald-600', aspectRatio: '1/1', status: 'approved',
        notes: '8ft straight backdrop with endcap — printed and ready for the conference',
        tags: ['booth', 'banner', 'print', '8ft'],
        physicalSize: { w: 8, h: 8, unit: 'ft' },
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_Backdrop_8ft_Thumb.jpg',
        mapPosition: { x: 55, y: 470 },
      },
      {
        id: 'a-g-b9', title: 'Table Throw',
        type: 'tablecloth', category: 'booth',
        previewColor: 'bg-emerald-500', aspectRatio: '2/1', status: 'approved',
        notes: '8ft full table throw — printed and ready for the conference',
        tags: ['booth', 'tablecloth', 'print', '8ft'],
        physicalSize: { w: 8, h: 4, unit: 'ft' },
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_TableThrow_8ft_Thumb.jpg',
        mapPosition: { x: 235, y: 730 },
      },
      {
        id: 'a-g-b2', title: 'Tabletop Sign',
        type: 'booth', category: 'booth',
        previewColor: 'bg-emerald-400', aspectRatio: '5/6', status: 'review',
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_TabletopSign_Thumb.png',
        notes: 'Manage Enrollments. Simplify Communication. Support Families.\n\nVisit PreK.Club for a live demo.',
        tags: ['booth', 'print', 'signage'],
        physicalSize: { w: 8.5, h: 11, unit: 'in' },
        mapPosition: { x: 235, y: 470 },
      },
      {
        id: 'a-g-b3', title: 'TV Demo Loop',
        type: 'mockup', category: 'booth',
        previewColor: 'bg-teal-500', aspectRatio: '16/9', status: 'review',
        previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_TVDemoLoop_Thumb.png',
        notes: 'Looping product demo video/slideshow for TV display at booth',
        tags: ['booth', 'digital', 'demo'],
        mapPosition: { x: 415, y: 470 },
      },
      {
        id: 'a-g-b8', title: 'Stickers / Swag',
        type: 'swag', category: 'booth',
        previewColor: 'bg-emerald-300', aspectRatio: '1/1', status: 'approved',
        notes: 'Branded stickers and swag items for 300 attendees',
        tags: ['booth', 'swag', 'print'],
        physicalSize: { w: 2, h: 2, unit: 'in' },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/PreKClub_Conference_Sticker_PRINT_2x2.pdf',
          filename: 'PreKClub_Conference_Sticker_PRINT_2x2.pdf',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/PreKClub_Conference_Sticker_PRINT_2x2.jpg',
        },
        mapPosition: { x: 235, y: 590 },
      },

      // ── CONTENT ──────────────────────────────────────────────
      {
        id: 'a-g-c1', title: 'Sponsor Announcement Copy',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-500', aspectRatio: '4/3', status: 'review',
        notes: 'PreK.Club is proud to sponsor the 2026 FACCM & APPLE Accreditation Conference in Orlando, FL. 🌴\n\nWe\'re excited to connect with early learning leaders across Florida and share modern tools that help providers simplify enrollment, attendance, payments, and family communication.\n\nStop by to explore live demos, discover new features, and see how PreK.Club helps programs grow with confidence.\n\n📍 Loews Sapphire Falls Resort\n📅 June 19–20, 2026\n\n#FACCM2026 #APPLEAccreditation #PreKClub #EarlyLearning #ChildCare #ChildCareManagement',
        tags: ['content', 'copy', 'linkedin', 'announcement'],
        mapPosition: { x: 665, y: 495 },
      },
      {
        id: 'a-g-c2', title: 'CTA Messaging',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-400', aspectRatio: '4/3', status: 'review',
        notes: 'Primary CTA: Book a Live Demo\nSecondary CTA: Explore PreK.Club\nEvent CTA: Visit Us at FACCM & APPLE 2026\n\nQR CTAs: Scan to Explore PreK.Club / Book a Demo / Learn More / Connect With Our Team\n\nBooth signage: Manage Enrollments. Simplify Communication. Support Families. Visit PreK.Club for a live demo.\n\nHeadline options: The Child Care Software to Grow Your Program / Enrollment, Payments & Communication — All in One Place / Helping Child Care Programs Grow with Confidence / Simplify Child Care Management\n\nFeature labels: Enrollment · Payments · Family Communication · Attendance',
        tags: ['content', 'copy', 'cta', 'booth', 'signage'],
        mapPosition: { x: 845, y: 495 },
      },
      {
        id: 'a-g-c3', title: 'Social Captions',
        type: 'copy', category: 'content',
        previewColor: 'bg-orange-400', aspectRatio: '4/3', status: 'review',
        notes: 'IG/FB: We\'re excited to be part of the 2026 FACCM & APPLE Accreditation Conference. Stop by and discover how PreK.Club helps providers simplify enrollment, communication, and school management — all in one place. 📍 Orlando, FL 📅 June 19–20\n\nStory — See You There: See you at FACCM & APPLE 2026 👋 Visit the PreK.Club booth for live demos, new tools, and conversations about the future of early learning management.\n\nStory — Countdown: 3 days until FACCM & APPLE 2026 ✨ We\'re getting ready for live demos, new connections, and exciting conversations with providers across Florida.',
        tags: ['content', 'copy', 'social', 'instagram', 'facebook'],
        mapPosition: { x: 665, y: 635 },
      },
      {
        id: 'a-g-c4', title: 'Demo Talking Points',
        type: 'copy', category: 'content',
        previewColor: 'bg-orange-500', aspectRatio: '4/3', status: 'review',
        notes: '• Enrollment management\n• Parent communication\n• Attendance tracking\n• Payments and billing\n• Provider-friendly dashboards\n• Family experience\n• Mobile accessibility\n• Simplified workflows',
        tags: ['content', 'copy', 'demo', 'talking-points'],
        mapPosition: { x: 845, y: 635 },
      },
      {
        id: 'a-g-c5', title: 'Follow-Up Emails',
        type: 'email', category: 'content',
        previewColor: 'bg-yellow-500', aspectRatio: '4/3', status: 'review',
        notes: 'Thank you for visiting the PreK.Club booth at FACCM & APPLE 2026.\n\nWe\'d love to continue the conversation and show you how PreK.Club can support your program with enrollment management, communication tools, and streamlined operations.\n\nSchedule a personalized demo with our team.',
        tags: ['content', 'email', 'follow-up', 'post-event'],
        mapPosition: { x: 1025, y: 495 },
      },

      // ── SOCIAL (client logo files) ───────────────────────────
      {
        id: 'a-g-s4', title: 'IG / FB Feed — PreK.Club Brand Logo',
        type: 'social', category: 'social',
        previewColor: 'bg-blue-500', aspectRatio: '1/1', status: 'approved',
        notes: 'Client-provided brand logo asset for Instagram and Facebook feed posts',
        tags: ['social', 'logo', 'instagram', 'facebook'],
        mapPosition: { x: 55, y: 215 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_IGFBFeed_BrandLogo.png',
          filename: 'GLS2026_PreKClub_IGFBFeed_BrandLogo.png',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_IGFBFeed_BrandLogo.png',
        },
      },
      {
        id: 'a-g-s5', title: 'IG Story — PreK.Club Brand Logo',
        type: 'social', category: 'social',
        previewColor: 'bg-blue-300', aspectRatio: '9/16', status: 'approved',
        notes: 'Client-provided brand logo asset for Instagram Story marketing',
        tags: ['social', 'logo', 'instagram', 'story'],
        mapPosition: { x: 235, y: 215 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_IGStory_BrandLogo.png',
          filename: 'GLS2026_PreKClub_IGStory_BrandLogo.png',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_IGStory_BrandLogo.png',
        },
      },

      // ── BOOTH (final print deliverables) ─────────────────────
      {
        id: 'a-g-b5', title: 'Postcard',
        type: 'postcard', category: 'booth',
        previewColor: 'bg-emerald-600', aspectRatio: '5/7', status: 'review',
        notes: '5×7 in printed postcard for conference distribution — includes QR code linking to play.prek.club',
        tags: ['booth', 'postcard', 'print', '5x7'],
        physicalSize: { w: 5, h: 7, unit: 'in' },
        sides: [
          { label: 'Front', previewUrl: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_Postcard_5x7_Thumb.jpg' },
          { label: 'Back',  previewUrl: '/prints/grow-lead-succeed-2026/PreKClub-Postcard_5x7_Back.jpg' },
        ],
        relatedAssets: ['a-g-b6'],
        mapPosition: { x: 330, y: 590 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_Postcard_5x7_Print.pdf',
          filename: 'GLS2026_PreKClub_Postcard_5x7_Print.pdf',
          size: '5×7 in',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_Postcard_5x7_Thumb.jpg',
        },
      },
      {
        id: 'a-g-b7', title: 'SafetyPlug Print',
        type: 'swag', category: 'booth',
        previewColor: 'bg-purple-600', aspectRatio: '1/1', status: 'approved',
        notes: '1.25×1.25 in safety plug sticker with QR code — print-ready PDF for demo stations',
        tags: ['booth', 'safetyplug', 'print', 'swag'],
        physicalSize: { w: 1.25, h: 1.25, unit: 'in' },
        relatedAssets: ['a-g-d6'],
        mapPosition: { x: 500, y: 590 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/PreKClub_Conference_Safety_Plug_QR_PRINT_1.25x1.25_V4.pdf',
          filename: 'GLS2026_PreKClub_SafetyPlug_1.25x1.25_Print_V4.pdf',
          size: '1.25×1.25 in',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/PreKClub_Conference_Safety_Plug_QR_PRINT_1.25x1.25_V4_Thumb.jpg',
        },
      },

      // ── OPERATIONS (QR source files) ──────────────────────────
      {
        id: 'a-g-b6', title: 'QR Code — Postcard',
        type: 'qr', category: 'digital',
        previewColor: 'bg-emerald-800', aspectRatio: '1/1', status: 'approved',
        physicalSize: { w: 1.5, h: 1.5, unit: 'in' },
        notes: 'QR code source file for the postcard — links to play.prek.club with UTM tracking',
        tags: ['operations', 'qr', 'postcard', 'source'],
        relatedAssets: ['a-g-b5'],
        mapPosition: { x: 1325, y: 550 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/play.prek.club_utm_source_postcard_utm_medium_qr.svg',
          filename: 'GLS2026_PreKClub_QR_Postcard.svg',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/play.prek.club_utm_source_postcard_utm_medium_qr.svg',
        },
      },
      {
        id: 'a-g-d6', title: 'QR Code — SafetyPlug',
        type: 'qr', category: 'digital',
        previewColor: 'bg-purple-800', aspectRatio: '1/1', status: 'approved',
        physicalSize: { w: 1.25, h: 1.25, unit: 'in' },
        notes: 'QR code source file for the SafetyPlug sticker — links to play.prek.club with UTM tracking',
        tags: ['operations', 'qr', 'safetyplug', 'source'],
        relatedAssets: ['a-g-b7'],
        mapPosition: { x: 1410, y: 550 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/play.prek.club_utm_source_safetyplug_utm_medium_qr.svg',
          filename: 'GLS2026_PreKClub_QR_SafetyPlug.svg',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/play.prek.club_utm_source_safetyplug_utm_medium_qr.svg',
        },
      },
      {
        id: 'a-g-o1', title: 'Lead Collection Workflow',
        type: 'workflow', category: 'operations',
        previewColor: 'bg-rose-500', aspectRatio: '4/3', status: 'in-design',
        notes: 'Flow: QR Scan → Landing Page → Demo / Contact Form → Thank-You Page → CRM / Email Capture → Follow-Up Campaign → Demo Scheduling\n\nEntry points\n- Booth QR — main conference scans\n- Demo form — scheduled interest\n- Tabletop QR — quick conversations\n- Business cards — manual contacts\n- Social traffic — LinkedIn / Instagram visitors\n\nLead categories\n- Hot Lead: requested demo or meeting\n- Warm Lead: interested, no immediate action\n- Partner / Org: networking or collaboration\n- Existing Client: current relationship\n\nCapture fields: Name · Email · Phone · Program Name · Role · # Students · Current Software · Interested Features\n\nFollow-up timeline\n- Same day: thank-you email + resource links + demo CTA\n- 2–3 days: personalized follow-up + walkthrough invitation\n- 1 week: reminder CTA + feature highlights + case study\n\nDuring conference: export leads daily · mark hot leads · assign follow-up owners\nAfter conference: segment leads · start nurturing · schedule demos · review conversions',
        tags: ['operations', 'leads', 'workflow'],
        mapPosition: { x: 1325, y: 495 },
      },
    ],
  },

  {
    id: 'born-to-teach-2026',
    title: 'Born to Teach Con 2026',
    organization: 'Born to Teach Con',
    date: '2026-07-01',
    location: 'Rosenberg, TX',
    audience: 'Early childhood educators, teachers',
    objective: 'Increase PreK.Club awareness and engagement through QR-driven swag bag materials distributed to conference educators',
    company: 'PreK.Club',
    presence: 'Swag Bag Sponsor',
    status: 'planning',
    progress: 10,
    coverGradient: 'from-emerald-400 to-teal-600',
    notes: `Swag bag items approved by conference organizer:
- 5×7 double-sided postcard (600 qty)
- Microfiber glass cleaner — PreK.Club branded, double-sided (600 qty)

Shipping address:
5728 Avenue I, Rosenberg, TX 77471

Delivery deadline: June 15, 2026

QR URL: https://play.prek.club/?utm_source=microfiber&utm_medium=qr

Messaging direction:
- Simplify childcare management
- Connect families and providers
- Modern tools for educators
- Mobile-friendly platform
- Community and growth focused
- Friendly and approachable tone`,
    tags: ['prekclub', 'swag-bag', 'print', 'texas', 'educator', 'postcard', 'swag', 'summer'],
    links: [
      { label: 'Born to Teach Con', url: 'https://www.borntoteachcon.com' },
    ],
    contacts: [
      { name: 'Semone Montelongo', role: 'Sponsorship Coordinator — Born to Teach Con', website: 'borntoteachcon.com', group: 'Event / Organization' },
      { name: 'Natalia Coletti', role: '', group: 'Internal Team' },
      { name: 'Carlos M. Valdes', role: '', group: 'Internal Team' },
      { name: 'Heidy Valdes', role: '', group: 'Internal Team' },
      { name: 'Abel Ferro', role: '', group: 'Internal Team' },
    ],
    deadlines: [
      { id: 'dl-bt0a', title: 'Campaign brief / messaging direction locked', date: '2026-05-10', type: 'other', done: true },
      { id: 'dl-bt0b', title: 'Postcard concept designed (front & back)', date: '2026-05-20', type: 'design', done: false },
      { id: 'dl-bt0c', title: 'Microfiber cleaner concept designed (both sides)', date: '2026-05-22', type: 'design', done: false },
      { id: 'dl-bt0d', title: 'QR tracking asset generated', date: '2026-05-22', type: 'design', done: false },
      { id: 'dl-bt1',  title: 'All designs approved', date: '2026-05-28', type: 'review', done: false },
      { id: 'dl-bt2',  title: 'Print-ready files prepared', date: '2026-06-01', type: 'print', done: false },
      { id: 'dl-bt3',  title: 'Proofs approved', date: '2026-06-05', type: 'review', done: false },
      { id: 'dl-bt4',  title: 'Order placed — 600 postcards + 600 microfiber cleaners', date: '2026-06-05', type: 'other', done: false },
      { id: 'dl-bt5',  title: 'Items shipped to Rosenberg, TX', date: '2026-06-15', type: 'shipping', done: false },
      { id: 'dl-bt6',  title: 'Born to Teach Con 2026', date: '2026-07-01', type: 'conference', done: false },
    ],
    assets: [
      // ── SOCIAL ──────────────────────────────────────────────
      {
        id: 'a-bt-s1', title: 'LinkedIn Sponsor Post',
        type: 'social', category: 'social',
        previewColor: 'bg-emerald-600', aspectRatio: '4/5', status: 'pending',
        notes: 'Sponsor announcement for Born to Teach Con 2026 — PreK.Club, educator-focused angle',
        tags: ['social', 'linkedin', 'sponsorship', 'announcement'],
        mapPosition: { x: 55, y: 75 },
      },
      {
        id: 'a-bt-s2', title: 'Post-Event Recap',
        type: 'social', category: 'social',
        previewColor: 'bg-teal-400', aspectRatio: '3/4', status: 'pending',
        notes: 'Post-conference recap post for social channels',
        tags: ['social', 'recap', 'post-event'],
        mapPosition: { x: 235, y: 75 },
      },

      // ── DIGITAL ─────────────────────────────────────────────
      {
        id: 'a-bt-d1', title: 'QR Code — Microfiber',
        type: 'qr', category: 'digital',
        previewColor: 'bg-slate-600', aspectRatio: '1/1', status: 'pending',
        notes: 'QR tracking URL:\nhttps://play.prek.club/?utm_source=microfiber&utm_medium=qr',
        tags: ['qr', 'digital', 'microfiber', 'source'],
        relatedAssets: ['a-bt-p3', 'a-bt-p4'],
        mapPosition: { x: 665, y: 75 },
        printFile: {
          url: '/prints/prekclub-shared/qr/play.prek.club_utm_source_microfiber_utm_medium_qr.svg',
          filename: 'BT2026_PreKClub_QR_Microfiber.svg',
          thumbnailUrl: '/prints/prekclub-shared/qr/play.prek.club_utm_source_microfiber_utm_medium_qr.svg',
        },
      },
      {
        id: 'a-bt-d2', title: 'QR Code — Postcard',
        type: 'qr', category: 'digital',
        previewColor: 'bg-emerald-800', aspectRatio: '1/1', status: 'approved',
        physicalSize: { w: 1.5, h: 1.5, unit: 'in' },
        notes: 'QR code source file for the postcard — links to play.prek.club with UTM tracking',
        tags: ['operations', 'qr', 'postcard', 'source'],
        relatedAssets: ['a-bt-b5'],
        mapPosition: { x: 845, y: 75 },
        printFile: {
          url: '/prints/prekclub-shared/qr/play.prek.club_utm_source_postcard_utm_medium_qr.svg',
          filename: 'BT2026_PreKClub_QR_Postcard.svg',
          thumbnailUrl: '/prints/prekclub-shared/qr/play.prek.club_utm_source_postcard_utm_medium_qr.svg',
        },
      },

      // ── PRINT ────────────────────────────────────────────────
      {
        id: 'a-bt-b5', title: 'Postcard',
        type: 'postcard', category: 'booth',
        previewColor: 'bg-emerald-600', aspectRatio: '5/7', status: 'review',
        notes: '5×7 in printed postcard for conference distribution — includes QR code linking to play.prek.club',
        tags: ['booth', 'postcard', 'print', '5x7'],
        physicalSize: { w: 5, h: 7, unit: 'in' },
        sides: [
          { label: 'Front', previewUrl: '/prints/prekclub-shared/postcard/PreKClub_Postcard_5x7_Front.jpg' },
          { label: 'Back',  previewUrl: '/prints/prekclub-shared/postcard/PreKClub_Postcard_5x7_Back.jpg' },
        ],
        relatedAssets: ['a-bt-d2'],
        mapPosition: { x: 55, y: 470 },
        printFile: {
          url: '/prints/prekclub-shared/postcard/PreKClub_Postcard_5x7_Print.pdf',
          filename: 'BT2026_PreKClub_Postcard_5x7_Print.pdf',
          size: '5×7 in',
          thumbnailUrl: '/prints/prekclub-shared/postcard/PreKClub_Postcard_5x7_Front.jpg',
        },
      },
      {
        id: 'a-bt-p3', title: 'Microfiber Glass Cleaner — Design',
        type: 'swag', category: 'booth',
        previewColor: 'bg-teal-500', aspectRatio: '3/2', status: 'pending',
        notes: 'Microfiber glass cleaner — double-sided\n• Minimal and clean design\n• Highly legible logo placement\n• QR code optional depending on printable area\nQty: 600',
        tags: ['swag', 'microfiber', 'print', 'swag-bag'],
        relatedAssets: ['a-bt-d1'],
        mapPosition: { x: 415, y: 470 },
      },
      {
        id: 'a-bt-p4', title: 'Microfiber Glass Cleaner — Print File',
        type: 'swag', category: 'booth',
        previewColor: 'bg-teal-700', aspectRatio: '3/2', status: 'pending',
        notes: 'Print-ready production file — CMYK, both sides, vendor specs\nQty: 600',
        tags: ['swag', 'microfiber', 'print', 'production'],
        relatedAssets: ['a-bt-d1'],
        mapPosition: { x: 235, y: 590 },
      },

      // ── CONTENT ──────────────────────────────────────────────
      {
        id: 'a-bt-c1', title: 'Copy — Postcard',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-500', aspectRatio: '4/3', status: 'pending',
        notes: 'Postcard messaging direction:\n• Simplify childcare management\n• Connect families and providers\n• Modern tools for educators\n• Mobile-friendly platform\n• Community and growth focused\n• Friendly and approachable tone\n\nCTA: Book a Demo / Explore PreK.Club\nQR: play.prek.club with UTM tracking',
        tags: ['content', 'copy', 'postcard'],
        mapPosition: { x: 665, y: 470 },
      },
    ],
  },

  {
    id: 'one-goal-summer-2026',
    title: 'One Goal Summer Conference',
    organization: 'FL Head Start Association',
    date: '2026-07-08',
    endDate: '2026-07-10',
    location: 'Tampa, FL',
    audience: 'Early Learning teachers, Early Learning Coalitions of Florida, State Administrators',
    objective: 'Good will WELS, Zipdata technology support',
    company: 'WELS / Zipdata',
    presence: 'Onsite',
    status: 'planning',
    progress: 5,
    coverGradient: 'from-sky-400 to-cyan-600',
    notes: '',
    tags: ['wels', 'zipdata', 'head-start', 'florida', 'tampa', 'summer'],
    links: [],
    contacts: [],
    deadlines: [
      { id: 'dl-ogs0a', title: 'Brand assets / logos received', date: '2026-05-20', type: 'other', done: false },
      { id: 'dl-ogs0b', title: 'Design concepts approved', date: '2026-05-28', type: 'design', done: false },
      { id: 'dl-ogs1',  title: 'LinkedIn sponsor post published', date: '2026-06-01', type: 'other', done: false },
      { id: 'dl-ogs2',  title: 'Print files to vendor', date: '2026-06-01', type: 'print', done: false },
      { id: 'dl-ogs3',  title: 'IG / FB pre-event post', date: '2026-06-05', type: 'other', done: false },
      { id: 'dl-ogs4',  title: 'Materials shipped to Tampa', date: '2026-06-20', type: 'shipping', done: false },
      { id: 'dl-ogs5',  title: 'Final prep check — all systems go', date: '2026-07-06', type: 'review', done: false },
      { id: 'dl-ogs6',  title: 'One Goal Summer Conference', date: '2026-07-08', type: 'conference', done: false },
      { id: 'dl-ogs7',  title: 'Post-event recap post', date: '2026-07-14', type: 'other', done: false },
    ],
    assets: [
      // ── SOCIAL ──────────────────────────────────────────────
      {
        id: 'a-ogs-s1', title: 'LinkedIn Sponsor Post',
        type: 'social', category: 'social',
        previewColor: 'bg-sky-600', aspectRatio: '4/5', status: 'pending',
        notes: 'Sponsor announcement — WELS + Zipdata branding, Early Learning angle',
        tags: ['social', 'linkedin', 'sponsorship', 'announcement'],
        mapPosition: { x: 55, y: 75 },
      },
      {
        id: 'a-ogs-s2', title: 'Instagram / Facebook Post',
        type: 'social', category: 'social',
        previewColor: 'bg-sky-400', aspectRatio: '4/5', status: 'pending',
        notes: 'Pre-event IG/FB feed post announcing conference attendance',
        tags: ['social', 'instagram', 'facebook', 'announcement'],
        mapPosition: { x: 235, y: 75 },
      },
      {
        id: 'a-ogs-s3', title: 'IG Story — See You There',
        type: 'social', category: 'social',
        previewColor: 'bg-cyan-500', aspectRatio: '9/16', status: 'pending',
        notes: 'Vertical story — booth location, dates, QR CTA',
        tags: ['social', 'instagram', 'story', 'promo'],
        mapPosition: { x: 415, y: 75 },
      },
      {
        id: 'a-ogs-s4', title: 'Post-Event Recap',
        type: 'social', category: 'social',
        previewColor: 'bg-cyan-400', aspectRatio: '3/4', status: 'pending',
        notes: 'Post-conference recap post for social channels',
        tags: ['social', 'recap', 'post-event'],
        mapPosition: { x: 415, y: 215 },
      },

      // ── DIGITAL ─────────────────────────────────────────────
      {
        id: 'a-ogs-d1', title: 'QR Code — Conference',
        type: 'qr', category: 'digital',
        previewColor: 'bg-slate-600', aspectRatio: '1/1', status: 'pending',
        notes: 'QR linking to WELS/Zipdata landing — UTM tracked',
        tags: ['qr', 'digital'],
        mapPosition: { x: 665, y: 75 },
      },

      // ── BOOTH ────────────────────────────────────────────────
      {
        id: 'a-ogs-b1', title: 'Banner — WELS',
        type: 'banner', category: 'booth',
        previewColor: 'bg-sky-500', aspectRatio: '1/3', status: 'pending',
        notes: 'Pull-up retractable banner — WELS branding',
        tags: ['banner', 'print', 'wels', 'booth'],
        mapPosition: { x: 55, y: 470 },
      },
      {
        id: 'a-ogs-b2', title: 'Tablecloth — Zipdata',
        type: 'tablecloth', category: 'booth',
        previewColor: 'bg-cyan-600', aspectRatio: '2/1', status: 'pending',
        notes: '6ft table throw — Zipdata branding',
        tags: ['tablecloth', 'print', 'zipdata', 'booth'],
        mapPosition: { x: 235, y: 470 },
      },
      {
        id: 'a-ogs-b3', title: 'Ad — Conference',
        type: 'ad', category: 'booth',
        previewColor: 'bg-sky-300', aspectRatio: '4/3', status: 'pending',
        notes: 'Conference ad — print or digital format TBD',
        tags: ['ad', 'print'],
        mapPosition: { x: 415, y: 470 },
      },
      {
        id: 'a-ogs-b4', title: 'Swag — 700 Attendees',
        type: 'swag', category: 'booth',
        previewColor: 'bg-cyan-300', aspectRatio: '1/1', status: 'pending',
        notes: 'Swag items for 700 conference attendees — items TBD',
        tags: ['swag', 'giveaway', 'booth'],
        mapPosition: { x: 235, y: 590 },
      },

      // ── CONTENT ──────────────────────────────────────────────
      {
        id: 'a-ogs-c1', title: 'Sponsor Copy',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-500', aspectRatio: '4/3', status: 'pending',
        notes: 'Announcement copy for LinkedIn and social posts',
        tags: ['content', 'copy', 'linkedin'],
        mapPosition: { x: 665, y: 470 },
      },
      {
        id: 'a-ogs-c2', title: 'Talking Points',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Booth talking points — WELS + Zipdata technology for ELC and Head Start audience',
        tags: ['content', 'copy', 'talking-points'],
        mapPosition: { x: 845, y: 470 },
      },
    ],
  },

  {
    id: 'annual-leadership-2026',
    title: '2026 Annual Leadership Conference',
    organization: "Florida Alliance of Children's Councils & Trusts",
    date: '2026-07-29',
    endDate: '2026-07-31',
    location: 'Daytona, FL',
    audience: 'CSC of Florida (Children Trusts)',
    objective: 'Good Will WELS',
    company: 'WELS',
    presence: 'Onsite',
    status: 'planning',
    progress: 5,
    coverGradient: 'from-teal-500 to-emerald-700',
    notes: '',
    tags: ['wels', 'florida', 'daytona', 'leadership', 'children-trusts', 'summer'],
    links: [],
    contacts: [],
    deadlines: [
      { id: 'dl-al0a', title: 'Brand direction confirmed', date: '2026-06-01', type: 'other', done: false },
      { id: 'dl-al0b', title: 'Design assets approved', date: '2026-06-10', type: 'design', done: false },
      { id: 'dl-al1',  title: 'Print files to vendor', date: '2026-06-15', type: 'print', done: false },
      { id: 'dl-al2',  title: 'LinkedIn sponsor post published', date: '2026-06-18', type: 'other', done: false },
      { id: 'dl-al3',  title: 'IG / FB pre-event post', date: '2026-06-22', type: 'other', done: false },
      { id: 'dl-al4',  title: 'Materials shipped to Daytona', date: '2026-07-10', type: 'shipping', done: false },
      { id: 'dl-al5',  title: 'Final prep check — all systems go', date: '2026-07-27', type: 'review', done: false },
      { id: 'dl-al6',  title: '2026 Annual Leadership Conference', date: '2026-07-29', type: 'conference', done: false },
      { id: 'dl-al7',  title: 'Post-event recap post', date: '2026-08-04', type: 'other', done: false },
    ],
    assets: [
      // ── SOCIAL ──────────────────────────────────────────────
      {
        id: 'a-al-s1', title: 'LinkedIn Sponsor Post',
        type: 'social', category: 'social',
        previewColor: 'bg-teal-600', aspectRatio: '4/5', status: 'pending',
        notes: 'Sponsor announcement — WELS branding, CSC of Florida audience',
        tags: ['social', 'linkedin', 'sponsorship', 'announcement'],
        mapPosition: { x: 55, y: 75 },
      },
      {
        id: 'a-al-s2', title: 'Instagram / Facebook Post',
        type: 'social', category: 'social',
        previewColor: 'bg-teal-400', aspectRatio: '4/5', status: 'pending',
        notes: 'Pre-event IG/FB feed post announcing conference attendance',
        tags: ['social', 'instagram', 'facebook', 'announcement'],
        mapPosition: { x: 235, y: 75 },
      },
      {
        id: 'a-al-s3', title: 'IG Story — See You There',
        type: 'social', category: 'social',
        previewColor: 'bg-emerald-500', aspectRatio: '9/16', status: 'pending',
        notes: 'Vertical story — booth location, dates, CTA',
        tags: ['social', 'instagram', 'story', 'promo'],
        mapPosition: { x: 415, y: 75 },
      },
      {
        id: 'a-al-s4', title: 'Post-Event Recap',
        type: 'social', category: 'social',
        previewColor: 'bg-emerald-400', aspectRatio: '3/4', status: 'pending',
        notes: 'Post-conference recap post for social channels',
        tags: ['social', 'recap', 'post-event'],
        mapPosition: { x: 415, y: 215 },
      },

      // ── DIGITAL ─────────────────────────────────────────────
      {
        id: 'a-al-d1', title: 'QR Code — Conference',
        type: 'qr', category: 'digital',
        previewColor: 'bg-slate-600', aspectRatio: '1/1', status: 'pending',
        notes: 'QR linking to WELS landing — UTM tracked',
        tags: ['qr', 'digital'],
        mapPosition: { x: 665, y: 75 },
      },

      // ── BOOTH ────────────────────────────────────────────────
      {
        id: 'a-al-b1', title: 'Banner — WELS',
        type: 'banner', category: 'booth',
        previewColor: 'bg-teal-500', aspectRatio: '1/3', status: 'pending',
        notes: 'Pull-up retractable banner — WELS branding',
        tags: ['banner', 'print', 'wels', 'booth'],
        mapPosition: { x: 55, y: 470 },
      },
      {
        id: 'a-al-b2', title: 'Ad — Conference',
        type: 'ad', category: 'booth',
        previewColor: 'bg-emerald-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Conference ad — format TBD',
        tags: ['ad', 'print'],
        mapPosition: { x: 235, y: 470 },
      },
      {
        id: 'a-al-b3', title: 'Swag — 150 Attendees',
        type: 'swag', category: 'booth',
        previewColor: 'bg-teal-300', aspectRatio: '1/1', status: 'pending',
        notes: 'Good swag for 150 attendees — items TBD',
        tags: ['swag', 'giveaway', 'booth'],
        mapPosition: { x: 235, y: 590 },
      },

      // ── CONTENT ──────────────────────────────────────────────
      {
        id: 'a-al-c1', title: 'Sponsor Copy',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-500', aspectRatio: '4/3', status: 'pending',
        notes: 'Announcement copy for LinkedIn and social posts',
        tags: ['content', 'copy', 'linkedin'],
        mapPosition: { x: 665, y: 470 },
      },
      {
        id: 'a-al-c2', title: 'Talking Points',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Booth talking points — WELS for CSC of Florida / Children Trusts audience',
        tags: ['content', 'copy', 'talking-points'],
        mapPosition: { x: 845, y: 470 },
      },
    ],
  },

  {
    id: 'nwra-2026',
    title: '2026 Annual Conference',
    organization: 'National Workforce Registry Alliance',
    date: '2026-10-01',
    location: 'Reno, NV',
    audience: '',
    objective: '',
    company: '',
    presence: '',
    status: 'planning',
    progress: 0,
    coverGradient: 'from-amber-500 to-orange-700',
    notes: '',
    tags: ['workforce-registry', 'reno', 'nevada', 'fall'],
    links: [],
    contacts: [],
    deadlines: [
      { id: 'dl-nw0',  title: 'Conference details confirmed (brand, presence, assets needed)', date: '2026-07-01', type: 'other', done: false },
      { id: 'dl-nw0b', title: 'Brand / campaign direction locked', date: '2026-08-01', type: 'design', done: false },
      { id: 'dl-nw1',  title: 'Print files to vendor', date: '2026-09-01', type: 'print', done: false },
      { id: 'dl-nw2',  title: 'Materials shipped to Reno', date: '2026-09-20', type: 'shipping', done: false },
      { id: 'dl-nw3',  title: 'NWRA Annual Conference', date: '2026-10-01', type: 'conference', done: false },
    ],
    assets: [
      {
        id: 'a-nw-s1', title: 'Attendance Announcement Post',
        type: 'social', category: 'social',
        previewColor: 'bg-amber-500', aspectRatio: '4/5', status: 'pending',
        notes: 'Social post announcing conference attendance — brand and copy TBD',
        tags: ['social', 'linkedin', 'announcement'],
        mapPosition: { x: 55, y: 75 },
      },
      {
        id: 'a-nw-b1', title: 'Banner — TBD',
        type: 'banner', category: 'booth',
        previewColor: 'bg-orange-500', aspectRatio: '1/3', status: 'pending',
        notes: 'Pull-up banner — brand and artwork TBD',
        tags: ['banner', 'print', 'booth'],
        mapPosition: { x: 55, y: 300 },
      },
      {
        id: 'a-nw-c1', title: 'Sponsor Copy — TBD',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Copy for announcements and booth — brand and objective TBD',
        tags: ['content', 'copy'],
        mapPosition: { x: 300, y: 300 },
      },
    ],
  },

  {
    id: 'aelc-2026',
    title: 'AELC Conference',
    organization: 'Florida Association of Early Learning Coalitions',
    date: '2026-11-01',
    location: 'Florida',
    audience: 'ELC of Florida',
    objective: 'Good will WELS/Zipdata',
    company: 'WELS / Zipdata',
    presence: 'Onsite',
    status: 'planning',
    progress: 5,
    coverGradient: 'from-green-500 to-teal-700',
    notes: '',
    tags: ['wels', 'zipdata', 'florida', 'early-learning', 'coalitions', 'fall'],
    links: [],
    contacts: [],
    deadlines: [
      { id: 'dl-aelc0a', title: 'Brand assets received', date: '2026-08-01', type: 'other', done: false },
      { id: 'dl-aelc0b', title: 'Design concepts approved', date: '2026-08-15', type: 'design', done: false },
      { id: 'dl-aelc1',  title: 'LinkedIn sponsor post published', date: '2026-08-25', type: 'other', done: false },
      { id: 'dl-aelc2',  title: 'Print files to vendor', date: '2026-09-01', type: 'print', done: false },
      { id: 'dl-aelc3',  title: 'IG / FB pre-event post', date: '2026-09-05', type: 'other', done: false },
      { id: 'dl-aelc4',  title: 'Materials shipped', date: '2026-10-15', type: 'shipping', done: false },
      { id: 'dl-aelc5',  title: 'Final prep check — all systems go', date: '2026-10-29', type: 'review', done: false },
      { id: 'dl-aelc6',  title: 'AELC Conference', date: '2026-11-01', type: 'conference', done: false },
      { id: 'dl-aelc7',  title: 'Post-event recap post', date: '2026-11-08', type: 'other', done: false },
    ],
    assets: [
      // ── SOCIAL ──────────────────────────────────────────────
      {
        id: 'a-aelc-s1', title: 'LinkedIn Sponsor Post',
        type: 'social', category: 'social',
        previewColor: 'bg-green-600', aspectRatio: '4/5', status: 'pending',
        notes: 'Sponsor announcement — WELS + Zipdata branding, ELC of Florida audience',
        tags: ['social', 'linkedin', 'sponsorship', 'announcement'],
        mapPosition: { x: 55, y: 75 },
      },
      {
        id: 'a-aelc-s2', title: 'Instagram / Facebook Post',
        type: 'social', category: 'social',
        previewColor: 'bg-green-400', aspectRatio: '4/5', status: 'pending',
        notes: 'Pre-event IG/FB feed post announcing conference attendance',
        tags: ['social', 'instagram', 'facebook', 'announcement'],
        mapPosition: { x: 235, y: 75 },
      },
      {
        id: 'a-aelc-s3', title: 'IG Story — See You There',
        type: 'social', category: 'social',
        previewColor: 'bg-teal-500', aspectRatio: '9/16', status: 'pending',
        notes: 'Vertical story — booth location, dates, CTA',
        tags: ['social', 'instagram', 'story', 'promo'],
        mapPosition: { x: 415, y: 75 },
      },
      {
        id: 'a-aelc-s4', title: 'Post-Event Recap',
        type: 'social', category: 'social',
        previewColor: 'bg-teal-400', aspectRatio: '3/4', status: 'pending',
        notes: 'Post-conference recap post for social channels',
        tags: ['social', 'recap', 'post-event'],
        mapPosition: { x: 415, y: 215 },
      },

      // ── DIGITAL ─────────────────────────────────────────────
      {
        id: 'a-aelc-d1', title: 'QR Code — Conference',
        type: 'qr', category: 'digital',
        previewColor: 'bg-slate-600', aspectRatio: '1/1', status: 'pending',
        notes: 'QR linking to WELS/Zipdata landing — UTM tracked',
        tags: ['qr', 'digital'],
        mapPosition: { x: 665, y: 75 },
      },

      // ── BOOTH ────────────────────────────────────────────────
      {
        id: 'a-aelc-b1', title: 'Banner — WELS',
        type: 'banner', category: 'booth',
        previewColor: 'bg-green-500', aspectRatio: '1/3', status: 'pending',
        notes: 'Pull-up retractable banner — WELS branding',
        tags: ['banner', 'print', 'wels', 'booth'],
        mapPosition: { x: 55, y: 470 },
      },
      {
        id: 'a-aelc-b2', title: 'Tablecloth',
        type: 'tablecloth', category: 'booth',
        previewColor: 'bg-teal-600', aspectRatio: '2/1', status: 'pending',
        notes: '6ft table throw — WELS or Zipdata branding TBD',
        tags: ['tablecloth', 'print', 'booth'],
        mapPosition: { x: 235, y: 470 },
      },
      {
        id: 'a-aelc-b3', title: 'Ad — Conference',
        type: 'ad', category: 'booth',
        previewColor: 'bg-green-300', aspectRatio: '4/3', status: 'pending',
        notes: 'Conference ad — print or digital format TBD',
        tags: ['ad', 'print'],
        mapPosition: { x: 415, y: 470 },
      },
      {
        id: 'a-aelc-b4', title: 'Swag — 500 Attendees',
        type: 'swag', category: 'booth',
        previewColor: 'bg-teal-300', aspectRatio: '1/1', status: 'pending',
        notes: 'Swag items for 500 attendees — items TBD',
        tags: ['swag', 'giveaway', 'booth'],
        mapPosition: { x: 235, y: 590 },
      },

      // ── CONTENT ──────────────────────────────────────────────
      {
        id: 'a-aelc-c1', title: 'Sponsor Copy',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-500', aspectRatio: '4/3', status: 'pending',
        notes: 'Announcement copy for LinkedIn and social posts',
        tags: ['content', 'copy', 'linkedin'],
        mapPosition: { x: 665, y: 470 },
      },
      {
        id: 'a-aelc-c2', title: 'Talking Points',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Booth talking points — WELS + Zipdata for ELC of Florida audience',
        tags: ['content', 'copy', 'talking-points'],
        mapPosition: { x: 845, y: 470 },
      },
    ],
  },

  {
    id: 'naeyc-2026',
    title: 'NAEYC Annual Conference',
    organization: 'National Association for the Education of Young Children',
    date: '2026-12-05',
    endDate: '2026-12-08',
    location: 'Washington, D.C.',
    audience: 'Educators, Directors, Org Admins',
    objective: 'Show childcare providers how to PreK',
    company: 'PreK.Club',
    presence: 'Onsite',
    status: 'planning',
    progress: 5,
    coverGradient: 'from-purple-500 to-violet-700',
    notes: '',
    tags: ['prekclub', 'naeyc', 'washington-dc', 'early-education', 'fall'],
    links: [],
    contacts: [],
    deadlines: [
      { id: 'dl-naeyc0a', title: 'Brand direction / campaign concept', date: '2026-07-15', type: 'design', done: false },
      { id: 'dl-naeyc0b', title: 'Design concepts approved', date: '2026-08-01', type: 'design', done: false },
      { id: 'dl-naeyc0c', title: 'Digital assets live (landing page, QR codes)', date: '2026-08-15', type: 'design', done: false },
      { id: 'dl-naeyc1',  title: 'LinkedIn sponsor post published', date: '2026-08-22', type: 'other', done: false },
      { id: 'dl-naeyc2',  title: 'Print files to vendor', date: '2026-09-01', type: 'print', done: false },
      { id: 'dl-naeyc3',  title: 'IG / FB pre-event post', date: '2026-09-10', type: 'other', done: false },
      { id: 'dl-naeyc4',  title: 'Materials shipped to Washington, D.C.', date: '2026-11-15', type: 'shipping', done: false },
      { id: 'dl-naeyc5',  title: 'Final prep check — all systems go', date: '2026-12-03', type: 'review', done: false },
      { id: 'dl-naeyc6',  title: 'NAEYC Annual Conference', date: '2026-12-05', type: 'conference', done: false },
      { id: 'dl-naeyc7',  title: 'Post-event recap post', date: '2026-12-12', type: 'other', done: false },
    ],
    assets: [
      // ── SOCIAL ──────────────────────────────────────────────
      {
        id: 'a-naeyc-s1', title: 'LinkedIn Sponsor Post',
        type: 'social', category: 'social',
        previewColor: 'bg-purple-600', aspectRatio: '4/5', status: 'pending',
        notes: 'Sponsor announcement — PreK.Club branding, show childcare providers how to PreK angle',
        tags: ['social', 'linkedin', 'sponsorship', 'announcement'],
        mapPosition: { x: 55, y: 75 },
      },
      {
        id: 'a-naeyc-s2', title: 'Instagram / Facebook Post',
        type: 'social', category: 'social',
        previewColor: 'bg-purple-400', aspectRatio: '4/5', status: 'pending',
        notes: 'Pre-event IG/FB feed post announcing conference attendance',
        tags: ['social', 'instagram', 'facebook', 'announcement'],
        mapPosition: { x: 235, y: 75 },
      },
      {
        id: 'a-naeyc-s3', title: 'IG Story — See You There',
        type: 'social', category: 'social',
        previewColor: 'bg-violet-500', aspectRatio: '9/16', status: 'pending',
        notes: 'Vertical story — booth location, dates, CTA',
        tags: ['social', 'instagram', 'story', 'promo'],
        mapPosition: { x: 415, y: 75 },
      },
      {
        id: 'a-naeyc-s4', title: 'IG Story — Countdown',
        type: 'social', category: 'social',
        previewColor: 'bg-purple-500', aspectRatio: '9/16', status: 'pending',
        notes: 'Countdown story variants — 5 days / 3 days / Tomorrow',
        tags: ['social', 'instagram', 'story', 'countdown'],
        mapPosition: { x: 235, y: 310 },
      },
      {
        id: 'a-naeyc-s5', title: 'Post-Event Recap',
        type: 'social', category: 'social',
        previewColor: 'bg-violet-400', aspectRatio: '3/4', status: 'pending',
        notes: 'Post-conference recap post for social channels',
        tags: ['social', 'recap', 'post-event'],
        mapPosition: { x: 415, y: 215 },
      },

      // ── DIGITAL ─────────────────────────────────────────────
      {
        id: 'a-naeyc-d1', title: 'Conference Landing Page',
        type: 'landing', category: 'digital',
        previewColor: 'bg-violet-600', aspectRatio: '16/9', status: 'pending',
        notes: 'Conference-specific landing page for PreK.Club — QR destination, demo CTA',
        tags: ['digital', 'web', 'landing'],
        mapPosition: { x: 665, y: 75 },
      },
      {
        id: 'a-naeyc-d2', title: 'Thank-You Page',
        type: 'landing', category: 'digital',
        previewColor: 'bg-violet-400', aspectRatio: '5/3', status: 'pending',
        notes: 'Post-form thank-you page with next steps and demo CTA',
        tags: ['digital', 'web'],
        mapPosition: { x: 845, y: 75 },
      },
      {
        id: 'a-naeyc-d3', title: 'QR Code — Booth',
        type: 'qr', category: 'digital',
        previewColor: 'bg-slate-600', aspectRatio: '1/1', status: 'pending',
        notes: 'QR linking to landing page — UTM tracked',
        tags: ['qr', 'digital'],
        mapPosition: { x: 1025, y: 75 },
      },

      // ── BOOTH ────────────────────────────────────────────────
      {
        id: 'a-naeyc-b1', title: 'Banner — PreK.Club',
        type: 'banner', category: 'booth',
        previewColor: 'bg-purple-500', aspectRatio: '1/3', status: 'pending',
        notes: 'Pull-up retractable banner — PreK.Club branding',
        tags: ['banner', 'print', 'prekclub', 'booth'],
        mapPosition: { x: 55, y: 470 },
      },
      {
        id: 'a-naeyc-b2', title: 'Tabletop Sign',
        type: 'booth', category: 'booth',
        previewColor: 'bg-violet-400', aspectRatio: '5/6', status: 'pending',
        notes: 'Quick-scan interaction point — 3 benefits + QR + CTA',
        tags: ['booth', 'print', 'signage'],
        mapPosition: { x: 235, y: 470 },
      },
      {
        id: 'a-naeyc-b3', title: 'Ad — Conference',
        type: 'ad', category: 'booth',
        previewColor: 'bg-purple-300', aspectRatio: '4/3', status: 'pending',
        notes: 'Conference ad — format TBD',
        tags: ['ad', 'print'],
        mapPosition: { x: 415, y: 470 },
      },
      {
        id: 'a-naeyc-b4', title: 'Swag — 2000 Attendees',
        type: 'swag', category: 'booth',
        previewColor: 'bg-violet-300', aspectRatio: '1/1', status: 'pending',
        notes: 'Swag items for 2000 attendees — items TBD',
        tags: ['swag', 'giveaway', 'booth'],
        mapPosition: { x: 235, y: 590 },
      },

      // ── CONTENT ──────────────────────────────────────────────
      {
        id: 'a-naeyc-c1', title: 'Sponsor Copy',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-500', aspectRatio: '4/3', status: 'pending',
        notes: 'Announcement copy for LinkedIn and social posts — PreK.Club, how to PreK angle',
        tags: ['content', 'copy', 'linkedin'],
        mapPosition: { x: 665, y: 470 },
      },
      {
        id: 'a-naeyc-c2', title: 'CTA Messaging',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Primary CTA: Book a Demo / Explore PreK.Club — Educators, Directors, Org Admins',
        tags: ['content', 'copy', 'cta'],
        mapPosition: { x: 845, y: 470 },
      },
      {
        id: 'a-naeyc-c3', title: 'Talking Points',
        type: 'copy', category: 'content',
        previewColor: 'bg-orange-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Booth talking points — show childcare providers how to PreK, enrollment, payments, communication',
        tags: ['content', 'copy', 'talking-points'],
        mapPosition: { x: 1025, y: 470 },
      },
    ],
  },

  {
    id: 'mdhs-better-together-2026',
    title: 'MDHS – Better Together',
    organization: 'MDHS',
    date: '2026-12-01',
    location: 'Mississippi',
    audience: 'Coaches / TA Providers',
    objective: 'Promote WELS — do a family portal',
    company: 'WELS',
    presence: 'Onsite MS Team',
    status: 'planning',
    progress: 5,
    coverGradient: 'from-blue-600 to-indigo-800',
    notes: '',
    tags: ['wels', 'mississippi', 'mdhs', 'coaches', 'family-portal', 'fall'],
    links: [],
    contacts: [],
    deadlines: [
      { id: 'dl-mdhs0a', title: 'Brand assets confirmed', date: '2026-08-15', type: 'other', done: false },
      { id: 'dl-mdhs0b', title: 'Design assets approved', date: '2026-09-15', type: 'design', done: false },
      { id: 'dl-mdhs1',  title: 'Print files to vendor', date: '2026-10-01', type: 'print', done: false },
      { id: 'dl-mdhs2',  title: 'LinkedIn post published', date: '2026-10-10', type: 'other', done: false },
      { id: 'dl-mdhs3',  title: 'IG / FB pre-event post', date: '2026-10-15', type: 'other', done: false },
      { id: 'dl-mdhs4',  title: 'Materials shipped to Mississippi', date: '2026-11-10', type: 'shipping', done: false },
      { id: 'dl-mdhs5',  title: 'Final prep check — all systems go', date: '2026-11-28', type: 'review', done: false },
      { id: 'dl-mdhs6',  title: 'MDHS – Better Together', date: '2026-12-01', type: 'conference', done: false },
      { id: 'dl-mdhs7',  title: 'Post-event recap post', date: '2026-12-08', type: 'other', done: false },
    ],
    assets: [
      // ── SOCIAL ──────────────────────────────────────────────
      {
        id: 'a-mdhs-s1', title: 'LinkedIn Post',
        type: 'social', category: 'social',
        previewColor: 'bg-blue-600', aspectRatio: '4/5', status: 'pending',
        notes: 'Attendance announcement — WELS + family portal angle, MS coaches audience',
        tags: ['social', 'linkedin', 'announcement'],
        mapPosition: { x: 55, y: 75 },
      },
      {
        id: 'a-mdhs-s2', title: 'Instagram / Facebook Post',
        type: 'social', category: 'social',
        previewColor: 'bg-blue-400', aspectRatio: '4/5', status: 'pending',
        notes: 'Pre-event IG/FB post announcing conference attendance',
        tags: ['social', 'instagram', 'facebook', 'announcement'],
        mapPosition: { x: 235, y: 75 },
      },
      {
        id: 'a-mdhs-s3', title: 'Post-Event Recap',
        type: 'social', category: 'social',
        previewColor: 'bg-indigo-400', aspectRatio: '3/4', status: 'pending',
        notes: 'Post-conference recap post for social channels',
        tags: ['social', 'recap', 'post-event'],
        mapPosition: { x: 415, y: 75 },
      },

      // ── DIGITAL ─────────────────────────────────────────────
      {
        id: 'a-mdhs-d1', title: 'QR Code — Conference',
        type: 'qr', category: 'digital',
        previewColor: 'bg-slate-600', aspectRatio: '1/1', status: 'pending',
        notes: 'QR linking to WELS family portal — UTM tracked',
        tags: ['qr', 'digital'],
        mapPosition: { x: 665, y: 75 },
      },

      // ── BOOTH ────────────────────────────────────────────────
      {
        id: 'a-mdhs-b1', title: 'Banner — WELS',
        type: 'banner', category: 'booth',
        previewColor: 'bg-blue-600', aspectRatio: '1/3', status: 'pending',
        notes: 'Pull-up retractable banner — WELS branding',
        tags: ['banner', 'print', 'wels', 'booth'],
        mapPosition: { x: 55, y: 470 },
      },
      {
        id: 'a-mdhs-b2', title: 'Swag — 500 Attendees',
        type: 'swag', category: 'booth',
        previewColor: 'bg-indigo-400', aspectRatio: '1/1', status: 'pending',
        notes: 'Swag items for 500 attendees — items TBD',
        tags: ['swag', 'giveaway', 'booth'],
        mapPosition: { x: 235, y: 470 },
      },

      // ── CONTENT ──────────────────────────────────────────────
      {
        id: 'a-mdhs-c1', title: 'Sponsor Copy',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-500', aspectRatio: '4/3', status: 'pending',
        notes: 'Announcement copy for LinkedIn and social posts — WELS, family portal angle',
        tags: ['content', 'copy', 'linkedin'],
        mapPosition: { x: 665, y: 470 },
      },
      {
        id: 'a-mdhs-c2', title: 'Talking Points — Family Portal',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Booth talking points — WELS family portal for MS coaches and TA providers',
        tags: ['content', 'copy', 'talking-points'],
        mapPosition: { x: 845, y: 470 },
      },
    ],
  },

  {
    id: 'facct-alliance-2026',
    title: "FACCT — Florida Alliance of Children's Councils & Trusts",
    organization: "Florida Alliance of Children's Councils & Trusts",
    date: '2026-12-31',
    location: 'TBD',
    audience: 'Coaches / TA Providers',
    objective: '',
    company: '',
    presence: '',
    status: 'planning',
    progress: 0,
    coverGradient: 'from-rose-500 to-red-700',
    notes: '',
    tags: ['florida', 'alliance', 'councils', 'trusts'],
    links: [],
    contacts: [],
    deadlines: [
      { id: 'dl-facct0', title: 'Conference details confirmed (date, location, brand, presence, assets)', date: '2026-07-01', type: 'other', done: false },
    ],
    assets: [
      {
        id: 'a-facct-s1', title: 'Attendance Announcement Post',
        type: 'social', category: 'social',
        previewColor: 'bg-rose-500', aspectRatio: '4/5', status: 'pending',
        notes: 'Social post announcing attendance — brand and copy TBD',
        tags: ['social', 'linkedin', 'announcement'],
        mapPosition: { x: 55, y: 75 },
      },
      {
        id: 'a-facct-b1', title: 'Banner — TBD',
        type: 'banner', category: 'booth',
        previewColor: 'bg-red-500', aspectRatio: '1/3', status: 'pending',
        notes: 'Banner — brand and artwork TBD',
        tags: ['banner', 'print', 'booth'],
        mapPosition: { x: 55, y: 300 },
      },
      {
        id: 'a-facct-c1', title: 'Copy — TBD',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Announcement copy and talking points — brand and objective TBD',
        tags: ['content', 'copy'],
        mapPosition: { x: 300, y: 300 },
      },
    ],
  },
];

export const getEventById = (id: string) => events.find((e) => e.id === id);
