import type { Event } from '@/lib/types';

export const events: Event[] = [
  {
    id: 'caaeyc-2026',
    title: 'CAAEYC Annual Conference & Expo 2026',
    organization: 'California Association for the Education of Young Children',
    date: '2026-03-14',
    endDate: '2026-03-16',
    location: 'Pasadena Convention Center, Pasadena, CA',
    audience: 'Early childhood educators, directors, and administrators across California',
    objective: 'Showcase early education solutions with a full booth presence, distribute branded materials, and generate leads among ECE professionals',
    company: 'WELS',
    presence: 'Full 10x10 booth with tablecloth, banners, and swag distribution',
    status: 'archived',
    progress: 65,
    coverGradient: 'from-violet-500 to-purple-700',
    notes: 'Booth #412 confirmed. Need to finalize swag bag items and ensure banner prints arrive by Feb 28. Hotel block closes Feb 1.',
    tags: ['early-education', 'california', 'expo', 'booth', 'spring'],
    links: [
      { label: 'Conference Website', url: 'https://www.caaeyc.org/conference' },
      { label: 'Booth Registration', url: 'https://www.caaeyc.org/exhibitors' },
      { label: 'Hotel Block', url: 'https://marriott.com/lax' },
    ],
    contacts: [
      { name: 'Maria Santos', role: 'Event Coordinator', email: 'msantos@caaeyc.org' },
      { name: 'James Thornton', role: 'WELS Account Manager', email: 'jthornton@wels.com' },
      { name: 'Linda Park', role: 'Print Vendor Contact', email: 'linda@printpro.com' },
    ],
    deadlines: [
      { id: 'dl-c1', title: 'Banner design finalized', date: '2026-02-10', type: 'design', done: true },
      { id: 'dl-c2', title: 'Tablecloth artwork approved', date: '2026-02-14', type: 'review', done: true },
      { id: 'dl-c3', title: 'All print files to vendor', date: '2026-02-28', type: 'print', done: false },
      { id: 'dl-c4', title: 'Swag shipped to Pasadena hotel', date: '2026-03-08', type: 'shipping', done: false },
      { id: 'dl-c5', title: 'CAAEYC Conference', date: '2026-03-14', type: 'conference', done: false },
      { id: 'dl-c6', title: 'Post-event asset archive', date: '2026-03-20', type: 'other', done: false },
    ],
    assets: [
      {
        id: 'a-c1',
        title: '10ft Backdrop Banner',
        type: 'banner',
        previewColor: 'bg-violet-500',
        aspectRatio: '10/3',
        status: 'approved',
        notes: 'Horizontal banner for back of booth wall',
        tags: ['booth', 'print', 'banner'],
        mapPosition: { x: 80, y: 60 },
      },
      {
        id: 'a-c2',
        title: 'Pull-Up Retractable Banner',
        type: 'banner',
        previewColor: 'bg-purple-600',
        aspectRatio: '1/3',
        status: 'approved',
        notes: 'Tall vertical pull-up for booth entrance',
        tags: ['booth', 'print'],
        mapPosition: { x: 300, y: 80 },
      },
      {
        id: 'a-c3',
        title: 'Booth Tablecloth',
        type: 'tablecloth',
        previewColor: 'bg-indigo-500',
        aspectRatio: '2/1',
        status: 'approved',
        notes: '6ft table throw with logo front and center',
        tags: ['booth', 'print', 'table'],
        mapPosition: { x: 500, y: 200 },
      },
      {
        id: 'a-c4',
        title: 'Conference Landing Page',
        type: 'landing',
        previewColor: 'bg-violet-400',
        aspectRatio: '16/9',
        status: 'delivered',
        externalUrl: 'https://wels.com/caaeyc2026',
        notes: 'Landing page for QR scan from booth materials',
        tags: ['digital', 'web', 'landing'],
        mapPosition: { x: 750, y: 120 },
      },
      {
        id: 'a-c5',
        title: 'QR Code — Landing Page',
        type: 'qr',
        previewColor: 'bg-slate-700',
        aspectRatio: '1/1',
        status: 'delivered',
        notes: 'QR pointing to landing page, used on postcard and tablecloth',
        tags: ['digital', 'qr'],
        mapPosition: { x: 900, y: 300 },
      },
      {
        id: 'a-c6',
        title: 'Postcard Handout',
        type: 'postcard',
        previewColor: 'bg-fuchsia-500',
        aspectRatio: '3/2',
        status: 'in-design',
        notes: '4x6 postcard for booth handout — needs QR and copy finalized',
        tags: ['print', 'postcard', 'handout'],
        mapPosition: { x: 140, y: 350 },
      },
      {
        id: 'a-c7',
        title: 'Social Media — Event Announcement',
        type: 'social',
        previewColor: 'bg-pink-500',
        aspectRatio: '1/1',
        status: 'delivered',
        notes: 'Instagram + Facebook square post announcing attendance',
        tags: ['social', 'digital', 'instagram'],
        mapPosition: { x: 400, y: 420 },
      },
      {
        id: 'a-c8',
        title: 'Swag — Tote Bag Mockup',
        type: 'swag',
        previewColor: 'bg-amber-500',
        aspectRatio: '4/5',
        status: 'review',
        notes: 'Canvas tote with WELS logo — 200 qty',
        tags: ['swag', 'mockup', 'giveaway'],
        mapPosition: { x: 650, y: 480 },
      },
      {
        id: 'a-c9',
        title: 'Company Logo (Conference version)',
        type: 'logo',
        previewColor: 'bg-violet-700',
        aspectRatio: '3/1',
        status: 'approved',
        notes: 'Horizontal lockup for conference use, white and full-color variants',
        tags: ['logo', 'brand'],
        mapPosition: { x: 900, y: 560 },
      },
    ],
  },

  {
    id: 'annual-summit-2026',
    title: 'Annual Summit 2026',
    organization: 'BWELZ National Network',
    date: '2026-04-22',
    endDate: '2026-04-24',
    location: 'Orange County Convention Center, Orlando, FL',
    audience: 'Family childcare providers, network coordinators, and policy advocates',
    objective: 'Reinforce brand presence among network partners, unveil new platform features, and collect feedback from active users',
    company: 'BWELZ',
    presence: 'Sponsored breakout session + 10x20 exhibit hall booth',
    status: 'archived',
    progress: 30,
    coverGradient: 'from-orange-400 to-rose-600',
    notes: 'Breakout session confirmed for April 23 at 2pm. Need slide deck template and speaker bio for agenda. Exhibit hall booth adjacent to main entrance.',
    tags: ['summit', 'florida', 'network', 'booth', 'spring'],
    links: [
      { label: 'Summit Website', url: 'https://bwelz.org/summit2026' },
      { label: 'Speaker Portal', url: 'https://bwelz.org/speakers' },
    ],
    contacts: [
      { name: 'Darnell Brooks', role: 'Summit Director', email: 'dbrooks@bwelz.org' },
      { name: 'Priya Nair', role: 'BWELZ Marketing Lead', email: 'pnair@bwelz.com' },
    ],
    deadlines: [
      { id: 'dl-s1', title: 'Slide deck template designed', date: '2026-03-15', type: 'design', done: false },
      { id: 'dl-s2', title: 'Banner design review', date: '2026-03-28', type: 'review', done: false },
      { id: 'dl-s3', title: 'Print files submitted', date: '2026-04-05', type: 'print', done: false },
      { id: 'dl-s4', title: 'Materials shipped to Orlando', date: '2026-04-15', type: 'shipping', done: false },
      { id: 'dl-s5', title: 'Annual Summit 2026', date: '2026-04-22', type: 'conference', done: false },
    ],
    assets: [
      {
        id: 'a-s1',
        title: 'Booth Backdrop 10x20',
        type: 'banner',
        previewColor: 'bg-orange-500',
        aspectRatio: '20/6',
        status: 'in-design',
        notes: 'Wide-format backdrop for large booth',
        tags: ['booth', 'banner', 'print'],
        mapPosition: { x: 60, y: 80 },
      },
      {
        id: 'a-s2',
        title: 'Breakout Session Slides',
        type: 'pdf',
        previewColor: 'bg-rose-500',
        aspectRatio: '16/9',
        status: 'pending',
        notes: 'Slide template + speaker content for breakout',
        tags: ['slides', 'presentation', 'digital'],
        mapPosition: { x: 350, y: 100 },
      },
      {
        id: 'a-s3',
        title: 'Pull-Up Banner — Feature Announcement',
        type: 'banner',
        previewColor: 'bg-amber-500',
        aspectRatio: '1/3',
        status: 'pending',
        notes: 'Highlight new platform features for summit audience',
        tags: ['banner', 'booth'],
        mapPosition: { x: 600, y: 80 },
      },
      {
        id: 'a-s4',
        title: 'Social — Summit Attendance Post',
        type: 'social',
        previewColor: 'bg-pink-400',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'Pre-event social post for LinkedIn + Instagram',
        tags: ['social', 'digital'],
        mapPosition: { x: 100, y: 350 },
      },
      {
        id: 'a-s5',
        title: 'Postcard — Platform Feature Highlight',
        type: 'postcard',
        previewColor: 'bg-orange-400',
        aspectRatio: '3/2',
        status: 'pending',
        notes: '5x7 postcard showcasing top 3 platform features',
        tags: ['print', 'postcard'],
        mapPosition: { x: 420, y: 380 },
      },
      {
        id: 'a-s6',
        title: 'QR Code — App Download',
        type: 'qr',
        previewColor: 'bg-slate-600',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'QR to app store download page',
        tags: ['qr', 'digital'],
        mapPosition: { x: 700, y: 420 },
      },
      {
        id: 'a-s7',
        title: 'Tablecloth — BWELZ Branded',
        type: 'tablecloth',
        previewColor: 'bg-rose-600',
        aspectRatio: '2/1',
        status: 'pending',
        notes: '6ft stretch tablecloth in brand colors',
        tags: ['booth', 'print', 'table'],
        mapPosition: { x: 900, y: 200 },
      },
    ],
  },

  {
    id: 'smart-start-2026',
    title: 'Smart Start Conference',
    organization: 'Smart Start NC',
    date: '2026-05-08',
    endDate: '2026-05-09',
    location: 'Raleigh Convention Center, Raleigh, NC',
    audience: 'Early childhood coalition members, county partners, funders, and policymakers',
    objective: 'Establish PreK.Club as a trusted platform for NC early childhood networks; generate partnership inquiries',
    company: 'PreK.Club',
    presence: 'Exhibitor table in networking hall',
    status: 'archived',
    progress: 20,
    coverGradient: 'from-emerald-400 to-teal-600',
    notes: 'Table in networking hall (not full booth). Simple setup — tablecloth, signage, and postcard stack. Budget is limited.',
    tags: ['north-carolina', 'early-childhood', 'coalition', 'spring'],
    links: [
      { label: 'Smart Start Conference', url: 'https://smartstart.org/conference' },
    ],
    contacts: [
      { name: 'Tamara Wells', role: 'Conference Chair', email: 'twells@smartstart.org' },
      { name: 'Oscar Reeves', role: 'PreK.Club Partner Lead', email: 'oreeves@prek.club' },
    ],
    deadlines: [
      { id: 'dl-ss1', title: 'Table signage designed', date: '2026-04-10', type: 'design', done: false },
      { id: 'dl-ss2', title: 'Postcard copy approved', date: '2026-04-18', type: 'review', done: false },
      { id: 'dl-ss3', title: 'Print files sent', date: '2026-04-25', type: 'print', done: false },
      { id: 'dl-ss4', title: 'Smart Start Conference', date: '2026-05-08', type: 'conference', done: false },
    ],
    assets: [
      {
        id: 'a-ss1',
        title: 'Table Sign — PreK.Club Intro',
        type: 'banner',
        previewColor: 'bg-emerald-500',
        aspectRatio: '4/3',
        status: 'pending',
        notes: 'Countertop table sign for exhibitor table',
        tags: ['signage', 'print', 'table'],
        mapPosition: { x: 80, y: 100 },
      },
      {
        id: 'a-ss2',
        title: 'Postcard — What is PreK.Club?',
        type: 'postcard',
        previewColor: 'bg-teal-500',
        aspectRatio: '3/2',
        status: 'pending',
        notes: 'Intro postcard with QR code to sign-up page',
        tags: ['print', 'postcard', 'intro'],
        mapPosition: { x: 320, y: 150 },
      },
      {
        id: 'a-ss3',
        title: 'QR Code — Signup Flow',
        type: 'qr',
        previewColor: 'bg-slate-600',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'QR to prek.club/smartstart registration flow',
        tags: ['qr', 'digital'],
        mapPosition: { x: 550, y: 200 },
      },
      {
        id: 'a-ss4',
        title: 'Social — NC Conference Announcement',
        type: 'social',
        previewColor: 'bg-green-500',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'LinkedIn post targeting NC early childhood network',
        tags: ['social', 'digital'],
        mapPosition: { x: 100, y: 400 },
      },
      {
        id: 'a-ss5',
        title: 'Tablecloth — PreK.Club Green',
        type: 'tablecloth',
        previewColor: 'bg-emerald-600',
        aspectRatio: '2/1',
        status: 'pending',
        notes: '6ft table throw in PreK.Club brand green',
        tags: ['booth', 'print'],
        mapPosition: { x: 700, y: 350 },
      },
      {
        id: 'a-ss6',
        title: 'One-pager PDF — Platform Overview',
        type: 'pdf',
        previewColor: 'bg-teal-400',
        aspectRatio: '8.5/11',
        status: 'pending',
        notes: 'Printable one-pager for county coordinators',
        tags: ['pdf', 'print', 'overview'],
        mapPosition: { x: 950, y: 150 },
      },
    ],
  },

  {
    id: 'grow-lead-succeed-2026',
    title: 'FACCM & APPLE - Grow. Lead. Succeed. 2026 Conference',
    organization: 'FACCM, APPLE',
    date: '2026-06-19',
    endDate: '2026-06-20',
    location: 'Loews Sapphire Falls Resort, Orlando, FL',
    audience: 'Site Admins, Leadership, Policy Makers',
    objective: 'Reach out to accredited providers in Florida to present a better way to manage their schools enrollments, payments, and communication with parents',
    company: 'PreK.Club',
    presence: 'Onsite',
    status: 'planning',
    progress: 15,
    coverGradient: 'from-blue-400 to-indigo-600',
    notes: `Primary focus: conference sponsorship visibility, provider outreach, and live product demos for PreK.Club.

Onsite team: Heidy Valdes and Natalia Colleti.
Main hall booth placement — high foot traffic expected.

Live demo station required with tablet/laptop setup.
Demo accounts, QR tracking, and lead capture workflow must be prepared before shipment.

Primary goals:
- Generate qualified provider leads
- Schedule demos
- Increase PreK.Club awareness
- Capture conference content for social media and post-event marketing`,
    tags: ['conference', 'sponsorship', 'prekclub', 'childcare', 'marketing', 'booth', 'demo', 'lead-generation', 'onsite', 'education', 'networking', 'summer'],
    links: [
      { label: 'GLS Conference', url: 'https://appleaccreditation.org/conference-2026/' },
      { label: 'Whova Event App', url: 'https://whova.com/web/C%40qggqv92hycv4%40D%40KL1kxnBpd4nAoFm4mxuhJojqBE%3D/' },
    ],
    contacts: [
      { name: 'Joyce Beauchamp', role: 'Digital Marketing & Events Manager — Florida Association for Child Care Management (FACCM)', email: 'jbeauchamp@faccm.org', phone: '954.869.7154 x3001', website: 'faccm.org', group: 'Event / Organization' },
      { name: 'Carlos M. Valdes', role: '', group: 'Internal Team' },
      { name: 'Heidy Valdes', role: '', group: 'Internal Team' },
      { name: 'Abel Ferro', role: '', group: 'Internal Team' },
      { name: 'Natalia Colleti', role: '', group: 'Internal Team' },
    ],
    deadlines: [
      { id: 'dl-g1',  title: 'Copy & messaging finalized (sponsor announcement, CTA, captions, talking points)', date: '2026-05-28', type: 'design', done: false },
      { id: 'dl-g2',  title: 'Digital assets live (landing page, QR code, booking form, thank-you page, GA4)', date: '2026-05-30', type: 'design', done: false },
      { id: 'dl-g3',  title: 'LinkedIn sponsor post published', date: '2026-05-30', type: 'other', done: false },
      { id: 'dl-g4',  title: 'Print design files ready (backdrop, tabletop sign, postcard, swag)', date: '2026-06-01', type: 'design', done: false },
      { id: 'dl-g5',  title: 'Instagram & Facebook pre-event post', date: '2026-06-02', type: 'other', done: false },
      { id: 'dl-g6',  title: 'Print files submitted to vendor', date: '2026-06-03', type: 'print', done: false },
      { id: 'dl-g7',  title: 'Materials shipped to Orlando', date: '2026-06-10', type: 'shipping', done: false },
      { id: 'dl-g8',  title: 'Lead collection workflow & demo accounts ready', date: '2026-06-15', type: 'review', done: false },
      { id: 'dl-g9',  title: 'Final prep check — all systems go', date: '2026-06-17', type: 'review', done: false },
      { id: 'dl-g10', title: 'FACCM & APPLE — Grow. Lead. Succeed. 2026 Conference', date: '2026-06-19', type: 'conference', done: false },
      { id: 'dl-g11', title: 'Post-event recap post + follow-up email sequence sent', date: '2026-06-23', type: 'other', done: false },
    ],
    assets: [
      // ── SOCIAL ──────────────────────────────────────────────
      {
        id: 'a-g-s1', title: 'LinkedIn Sponsor Post',
        type: 'social', category: 'social',
        previewColor: 'bg-blue-600', aspectRatio: '1.91/1', status: 'pending',
        notes: 'Sponsored post announcing PreK.Club presence at the conference',
        tags: ['social', 'linkedin', 'digital'],
        mapPosition: { x: 55, y: 75 },
      },
      {
        id: 'a-g-s2', title: 'Instagram / Facebook Post',
        type: 'social', category: 'social',
        previewColor: 'bg-blue-400', aspectRatio: '1/1', status: 'pending',
        notes: 'Pre-event announcement for IG and FB feeds',
        tags: ['social', 'instagram', 'facebook', 'digital'],
        mapPosition: { x: 235, y: 75 },
      },
      {
        id: 'a-g-s3', title: 'Post-Event Recap',
        type: 'social', category: 'social',
        previewColor: 'bg-sky-500', aspectRatio: '1.91/1', status: 'pending',
        notes: 'Recap post after the conference — highlights, photos, leads',
        tags: ['social', 'recap', 'digital'],
        mapPosition: { x: 415, y: 75 },
      },

      // ── DIGITAL ─────────────────────────────────────────────
      {
        id: 'a-g-d1', title: 'Conference Landing Page',
        type: 'landing', category: 'digital',
        previewColor: 'bg-violet-500', aspectRatio: '16/9', status: 'pending',
        notes: 'Dedicated landing page for the conference with PreK.Club info',
        tags: ['digital', 'web', 'landing'],
        mapPosition: { x: 665, y: 75 },
      },
      {
        id: 'a-g-d2', title: 'QR Code',
        type: 'qr', category: 'digital',
        previewColor: 'bg-violet-700', aspectRatio: '1/1', status: 'pending',
        notes: 'QR code linking to landing page or demo booking form',
        tags: ['digital', 'qr'],
        mapPosition: { x: 845, y: 75 },
      },
      {
        id: 'a-g-d3', title: 'Demo Booking Form',
        type: 'landing', category: 'digital',
        previewColor: 'bg-indigo-500', aspectRatio: '3/4', status: 'pending',
        notes: 'Form for attendees to book a live product demo',
        tags: ['digital', 'form', 'demo'],
        mapPosition: { x: 1025, y: 75 },
      },
      {
        id: 'a-g-d4', title: 'Thank-You Page',
        type: 'landing', category: 'digital',
        previewColor: 'bg-indigo-400', aspectRatio: '16/9', status: 'pending',
        notes: 'Post-form thank-you page with next steps',
        tags: ['digital', 'web'],
        mapPosition: { x: 665, y: 240 },
      },
      {
        id: 'a-g-d5', title: 'GA4 + QR Tracking',
        type: 'other', category: 'digital',
        previewColor: 'bg-purple-500', aspectRatio: '16/9', status: 'pending',
        notes: 'Analytics setup — UTM params, QR scan events, conversion goals',
        tags: ['digital', 'analytics', 'tracking'],
        mapPosition: { x: 845, y: 240 },
      },

      // ── BOOTH ────────────────────────────────────────────────
      {
        id: 'a-g-b1', title: 'Booth Backdrop',
        type: 'banner', category: 'booth',
        previewColor: 'bg-emerald-600', aspectRatio: '10/3', status: 'pending',
        notes: 'Full-width backdrop for the onsite booth',
        tags: ['booth', 'banner', 'print'],
        mapPosition: { x: 55, y: 470 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/GrowLeadSucceed_2026_PreKClub_Banner_Print.pdf',
          filename: 'GrowLeadSucceed_2026_PreKClub_Banner_Print.pdf',
          size: '—',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/GrowLeadSucceed_2026_PreKClub_Banner_Thumb.svg',
        },
      },
      {
        id: 'a-g-b2', title: 'Tabletop Sign',
        type: 'booth', category: 'booth',
        previewColor: 'bg-emerald-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Small tabletop sign for the booth table',
        tags: ['booth', 'print'],
        mapPosition: { x: 235, y: 470 },
      },
      {
        id: 'a-g-b3', title: 'TV Demo Loop',
        type: 'mockup', category: 'booth',
        previewColor: 'bg-teal-500', aspectRatio: '16/9', status: 'pending',
        notes: 'Looping product demo video/slideshow for TV display at booth',
        tags: ['booth', 'digital', 'demo'],
        mapPosition: { x: 415, y: 470 },
      },
      {
        id: 'a-g-b4', title: 'Postcard',
        type: 'postcard', category: 'booth',
        previewColor: 'bg-teal-400', aspectRatio: '3/2', status: 'pending',
        notes: 'Printed postcard handout for booth visitors',
        tags: ['booth', 'print', 'postcard'],
        mapPosition: { x: 55, y: 590 },
      },
      {
        id: 'a-g-b5', title: 'Stickers / Swag',
        type: 'swag', category: 'booth',
        previewColor: 'bg-emerald-300', aspectRatio: '1/1', status: 'pending',
        notes: 'Branded stickers and swag items for 300 attendees',
        tags: ['booth', 'swag', 'print'],
        mapPosition: { x: 235, y: 590 },
      },

      // ── CONTENT ──────────────────────────────────────────────
      {
        id: 'a-g-c1', title: 'Sponsor Announcement Copy',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-500', aspectRatio: '4/3', status: 'pending',
        notes: 'Written copy for sponsor announcement across channels',
        tags: ['content', 'copy'],
        mapPosition: { x: 665, y: 495 },
      },
      {
        id: 'a-g-c2', title: 'CTA Messaging',
        type: 'copy', category: 'content',
        previewColor: 'bg-amber-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Call-to-action messaging for ads, social, and print',
        tags: ['content', 'copy', 'cta'],
        mapPosition: { x: 845, y: 495 },
      },
      {
        id: 'a-g-c3', title: 'Social Captions',
        type: 'copy', category: 'content',
        previewColor: 'bg-orange-400', aspectRatio: '4/3', status: 'pending',
        notes: 'Caption drafts for each social post',
        tags: ['content', 'copy', 'social'],
        mapPosition: { x: 665, y: 635 },
      },
      {
        id: 'a-g-c4', title: 'Demo Talking Points',
        type: 'copy', category: 'content',
        previewColor: 'bg-orange-500', aspectRatio: '4/3', status: 'pending',
        notes: 'Key talking points for the booth demo presentation',
        tags: ['content', 'copy', 'demo'],
        mapPosition: { x: 845, y: 635 },
      },
      {
        id: 'a-g-c5', title: 'Follow-Up Emails',
        type: 'email', category: 'content',
        previewColor: 'bg-yellow-500', aspectRatio: '4/3', status: 'pending',
        notes: 'Post-event follow-up email sequence for captured leads',
        tags: ['content', 'email'],
        mapPosition: { x: 1025, y: 495 },
      },

      // ── SOCIAL (client logo files) ───────────────────────────
      {
        id: 'a-g-s4', title: 'IG / FB Feed — PreK.Club Brand Logo',
        type: 'social', category: 'social',
        previewColor: 'bg-blue-500', aspectRatio: '1/1', status: 'approved',
        notes: 'Client-provided brand logo asset for Instagram and Facebook feed posts',
        tags: ['social', 'logo', 'instagram', 'facebook'],
        mapPosition: { x: 55, y: 215 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_IGFBFeed_BrandLogo.png',
          filename: 'GLS2026_PreKClub_IGFBFeed_BrandLogo.png',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_IGFBFeed_BrandLogo.png',
        },
      },
      {
        id: 'a-g-s5', title: 'IG Story — PreK.Club Brand Logo',
        type: 'social', category: 'social',
        previewColor: 'bg-blue-300', aspectRatio: '9/16', status: 'approved',
        notes: 'Client-provided brand logo asset for Instagram Story marketing',
        tags: ['social', 'logo', 'instagram', 'story'],
        mapPosition: { x: 235, y: 215 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_IGStory_BrandLogo.png',
          filename: 'GLS2026_PreKClub_IGStory_BrandLogo.png',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/GLS2026_PreKClub_IGStory_BrandLogo.png',
        },
      },

      // ── BOOTH (final print deliverables) ─────────────────────
      {
        id: 'a-g-b5', title: 'Postcard',
        type: 'postcard', category: 'booth',
        previewColor: 'bg-emerald-600', aspectRatio: '3/2', status: 'in-design',
        notes: 'Printed postcard for conference distribution — includes QR code linking to play.prek.club',
        tags: ['booth', 'postcard', 'print'],
        relatedAssets: ['a-g-b6'],
        mapPosition: { x: 330, y: 590 },
      },
      {
        id: 'a-g-b7', title: 'SafetyPlug Print',
        type: 'swag', category: 'booth',
        previewColor: 'bg-purple-600', aspectRatio: '1/1', status: 'approved',
        notes: '1.25×1.25 in safety plug sticker with QR code — print-ready PDF for demo stations',
        tags: ['booth', 'safetyplug', 'print', 'swag'],
        relatedAssets: ['a-g-d6'],
        mapPosition: { x: 500, y: 590 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/PreKClub_Conference_Safety_Plug_QR_PRINT_1.25x1.25_V4.pdf',
          filename: 'GLS2026_PreKClub_SafetyPlug_1.25x1.25_Print_V4.pdf',
          size: '1.25×1.25 in',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/PreKClub_Conference_Safety_Plug_QR_PRINT_1.25x1.25_V4_Thumb.jpg',
        },
      },

      // ── OPERATIONS (QR source files) ──────────────────────────
      {
        id: 'a-g-b6', title: 'QR Code — Postcard',
        type: 'qr', category: 'operations',
        previewColor: 'bg-emerald-800', aspectRatio: '1/1', status: 'approved',
        notes: 'QR code source file for the postcard — links to play.prek.club with UTM tracking',
        tags: ['operations', 'qr', 'postcard', 'source'],
        relatedAssets: ['a-g-b5'],
        mapPosition: { x: 1325, y: 550 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/play.prek.club_utm_source_postcard_utm_medium_qr.svg',
          filename: 'GLS2026_PreKClub_QR_Postcard.svg',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/play.prek.club_utm_source_postcard_utm_medium_qr.svg',
        },
      },
      {
        id: 'a-g-d6', title: 'QR Code — SafetyPlug',
        type: 'qr', category: 'operations',
        previewColor: 'bg-purple-800', aspectRatio: '1/1', status: 'approved',
        notes: 'QR code source file for the SafetyPlug sticker — links to play.prek.club with UTM tracking',
        tags: ['operations', 'qr', 'safetyplug', 'source'],
        relatedAssets: ['a-g-b7'],
        mapPosition: { x: 1410, y: 550 },
        printFile: {
          url: '/prints/grow-lead-succeed-2026/play.prek.club_utm_source_safetyplug_utm_medium_qr.svg',
          filename: 'GLS2026_PreKClub_QR_SafetyPlug.svg',
          thumbnailUrl: '/prints/grow-lead-succeed-2026/play.prek.club_utm_source_safetyplug_utm_medium_qr.svg',
        },
      },
      {
        id: 'a-g-o1', title: 'Lead Collection Workflow',
        type: 'workflow', category: 'operations',
        previewColor: 'bg-rose-500', aspectRatio: '4/3', status: 'pending',
        notes: 'Process for capturing, tagging, and following up on leads at the conference',
        tags: ['operations', 'leads', 'workflow'],
        mapPosition: { x: 1325, y: 495 },
      },
    ],
  },

  {
    id: 'one-goal-summer-2026',
    title: 'One Goal Summer Conference',
    organization: 'WELS National Network',
    date: '2026-07-18',
    endDate: '2026-07-20',
    location: 'Hyatt Regency Chicago, Chicago, IL',
    audience: 'WELS network members, coaches, directors, and regional coordinators',
    objective: 'Celebrate network achievements, share best practices, and introduce new WELS tools and resources for the upcoming year',
    company: 'WELS',
    presence: 'Opening sponsor table + all-session signage',
    status: 'planning',
    progress: 10,
    coverGradient: 'from-sky-400 to-cyan-600',
    notes: 'Internal conference — all attendees are WELS affiliates. Focus on networking and tool adoption. Signage throughout hotel.',
    tags: ['wels', 'internal', 'chicago', 'network', 'summer'],
    links: [
      { label: 'One Goal Portal', url: 'https://wels.org/onegoal2026' },
    ],
    contacts: [
      { name: 'Carla Mendez', role: 'WELS Events Director', email: 'cmendez@wels.org' },
      { name: 'Mike Chen', role: 'Conference Logistics', email: 'mchen@wels.org' },
    ],
    deadlines: [
      { id: 'dl-og1', title: 'Signage concepts approved', date: '2026-06-10', type: 'design', done: false },
      { id: 'dl-og2', title: 'Print files to vendor', date: '2026-06-25', type: 'print', done: false },
      { id: 'dl-og3', title: 'Materials shipped to Chicago', date: '2026-07-10', type: 'shipping', done: false },
      { id: 'dl-og4', title: 'One Goal Summer Conference', date: '2026-07-18', type: 'conference', done: false },
    ],
    assets: [
      {
        id: 'a-og1',
        title: 'Welcome Banner — Hotel Lobby',
        type: 'banner',
        previewColor: 'bg-sky-500',
        aspectRatio: '3/1',
        status: 'pending',
        notes: 'Large welcome signage for Hyatt lobby entrance',
        tags: ['signage', 'banner', 'print'],
        mapPosition: { x: 80, y: 80 },
      },
      {
        id: 'a-og2',
        title: 'Session Room Sign Template',
        type: 'banner',
        previewColor: 'bg-cyan-500',
        aspectRatio: '4/3',
        status: 'pending',
        notes: 'Reusable template for breakout session rooms',
        tags: ['signage', 'template', 'print'],
        mapPosition: { x: 400, y: 100 },
      },
      {
        id: 'a-og3',
        title: 'Sponsor Table Tablecloth',
        type: 'tablecloth',
        previewColor: 'bg-sky-600',
        aspectRatio: '2/1',
        status: 'pending',
        notes: 'Opening sponsor table cover — WELS branding',
        tags: ['booth', 'print'],
        mapPosition: { x: 700, y: 200 },
      },
      {
        id: 'a-og4',
        title: 'Conference Program PDF',
        type: 'pdf',
        previewColor: 'bg-slate-500',
        aspectRatio: '8.5/11',
        status: 'pending',
        notes: 'Full multi-day program with sessions and bios',
        tags: ['pdf', 'program'],
        mapPosition: { x: 150, y: 400 },
      },
      {
        id: 'a-og5',
        title: 'Social — Conference Countdown',
        type: 'social',
        previewColor: 'bg-cyan-400',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'Series of 3 countdown posts for WELS social channels',
        tags: ['social', 'digital'],
        mapPosition: { x: 850, y: 500 },
      },
    ],
  },

  {
    id: 'nafcc-2026',
    title: 'NAFCC National Annual Conference',
    organization: 'National Association for Family Child Care',
    date: '2026-07-29',
    endDate: '2026-07-31',
    location: 'Caesars Palace, Las Vegas, NV',
    audience: 'Family childcare providers, accreditation specialists, and state coordinators',
    objective: 'Expand BWELZ brand awareness among accredited family childcare providers; drive platform trial sign-ups',
    company: 'BWELZ',
    presence: 'Exhibitor table + session sponsorship',
    status: 'planning',
    progress: 8,
    coverGradient: 'from-yellow-400 to-orange-500',
    notes: 'Las Vegas venue — shipping logistics need early planning. Session sponsorship includes logo on printed agenda.',
    tags: ['nafcc', 'family-childcare', 'las-vegas', 'accreditation', 'summer'],
    links: [
      { label: 'NAFCC Conference', url: 'https://nafcc.org/conference2026' },
      { label: 'Exhibitor Info', url: 'https://nafcc.org/exhibitors' },
    ],
    contacts: [
      { name: 'Stephanie Jordan', role: 'NAFCC Events Manager', email: 'sjordan@nafcc.org' },
      { name: 'Priya Nair', role: 'BWELZ Marketing Lead', email: 'pnair@bwelz.com' },
    ],
    deadlines: [
      { id: 'dl-n1', title: 'Logo submitted for printed agenda', date: '2026-06-15', type: 'design', done: false },
      { id: 'dl-n2', title: 'Table signage designed and approved', date: '2026-07-01', type: 'review', done: false },
      { id: 'dl-n3', title: 'Materials shipped to Las Vegas', date: '2026-07-20', type: 'shipping', done: false },
      { id: 'dl-n4', title: 'NAFCC Conference', date: '2026-07-29', type: 'conference', done: false },
    ],
    assets: [
      {
        id: 'a-n1',
        title: 'Pull-Up Banner — BWELZ Brand',
        type: 'banner',
        previewColor: 'bg-yellow-500',
        aspectRatio: '1/3',
        status: 'pending',
        notes: 'Standard retractable for exhibit table',
        tags: ['banner', 'booth', 'print'],
        mapPosition: { x: 90, y: 90 },
      },
      {
        id: 'a-n2',
        title: 'Tablecloth — BWELZ Yellow',
        type: 'tablecloth',
        previewColor: 'bg-orange-400',
        aspectRatio: '2/1',
        status: 'pending',
        notes: '4ft table throw in BWELZ yellow brand color',
        tags: ['booth', 'print'],
        mapPosition: { x: 350, y: 150 },
      },
      {
        id: 'a-n3',
        title: 'Session Sponsorship Logo',
        type: 'logo',
        previewColor: 'bg-yellow-600',
        aspectRatio: '3/1',
        status: 'pending',
        notes: 'High-res logo for printed agenda sponsorship block',
        tags: ['logo', 'brand', 'print'],
        mapPosition: { x: 650, y: 100 },
      },
      {
        id: 'a-n4',
        title: 'Postcard — Provider Sign-Up Offer',
        type: 'postcard',
        previewColor: 'bg-amber-400',
        aspectRatio: '3/2',
        status: 'pending',
        notes: 'Special offer postcard for conference attendees',
        tags: ['print', 'postcard', 'offer'],
        mapPosition: { x: 150, y: 400 },
      },
      {
        id: 'a-n5',
        title: 'Social — Las Vegas Conference Post',
        type: 'social',
        previewColor: 'bg-orange-500',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'Pre-event social announcement',
        tags: ['social', 'digital'],
        mapPosition: { x: 850, y: 380 },
      },
      {
        id: 'a-n6',
        title: 'QR Code — Free Trial',
        type: 'qr',
        previewColor: 'bg-slate-700',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'QR to free trial signup — used on postcard and tablecloth',
        tags: ['qr', 'digital'],
        mapPosition: { x: 500, y: 500 },
      },
    ],
  },

  {
    id: 'facct-2026',
    title: 'FACCT Florida Alliance Conference',
    organization: 'Florida Alliance for Child & Family Centers and Trusts',
    date: '2026-09-10',
    endDate: '2026-09-11',
    location: 'Tampa Convention Center, Tampa, FL',
    audience: 'Childcare center directors, family advocates, and Florida state agency staff',
    objective: 'Introduce Partner Hub as the central coordination platform for Florida childcare networks; gather pilot program interest',
    company: 'Partner Hub',
    presence: 'Exhibitor table in networking hall',
    status: 'planning',
    progress: 5,
    coverGradient: 'from-red-400 to-pink-600',
    notes: 'Fall conference in Tampa. Coordinator contact is Diane from FACCT. Networking hall is small — expect ~200 attendees.',
    tags: ['florida', 'alliance', 'childcare', 'fall', 'networking'],
    links: [
      { label: 'FACCT Website', url: 'https://facct.org/conference2026' },
    ],
    contacts: [
      { name: 'Diane Foster', role: 'FACCT Director', email: 'dfoster@facct.org' },
      { name: 'Sam Rivera', role: 'Partner Hub Outreach', email: 'srivera@partnerhub.io' },
    ],
    deadlines: [
      { id: 'dl-f1', title: 'Table materials designed', date: '2026-08-15', type: 'design', done: false },
      { id: 'dl-f2', title: 'Print files approved', date: '2026-08-28', type: 'review', done: false },
      { id: 'dl-f3', title: 'FACCT Conference', date: '2026-09-10', type: 'conference', done: false },
    ],
    assets: [
      {
        id: 'a-f1',
        title: 'Table Sign — Partner Hub',
        type: 'banner',
        previewColor: 'bg-red-500',
        aspectRatio: '4/3',
        status: 'pending',
        notes: 'Countertop foam board sign',
        tags: ['signage', 'print'],
        mapPosition: { x: 80, y: 100 },
      },
      {
        id: 'a-f2',
        title: 'Postcard — What is Partner Hub?',
        type: 'postcard',
        previewColor: 'bg-pink-500',
        aspectRatio: '3/2',
        status: 'pending',
        notes: 'Intro postcard with pilot program offer',
        tags: ['print', 'postcard'],
        mapPosition: { x: 350, y: 200 },
      },
      {
        id: 'a-f3',
        title: 'QR Code — Pilot Sign-Up',
        type: 'qr',
        previewColor: 'bg-slate-600',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'QR to pilot program interest form',
        tags: ['qr', 'digital'],
        mapPosition: { x: 650, y: 150 },
      },
      {
        id: 'a-f4',
        title: 'Social — Tampa Conference',
        type: 'social',
        previewColor: 'bg-rose-400',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'LinkedIn announcement of FACCT attendance',
        tags: ['social', 'digital'],
        mapPosition: { x: 200, y: 450 },
      },
      {
        id: 'a-f5',
        title: 'Tablecloth — Partner Hub Red',
        type: 'tablecloth',
        previewColor: 'bg-red-600',
        aspectRatio: '2/1',
        status: 'pending',
        notes: '6ft table throw',
        tags: ['booth', 'print'],
        mapPosition: { x: 850, y: 400 },
      },
    ],
  },

  {
    id: 'build-2026',
    title: 'BUILD',
    organization: 'ZipData Community',
    date: '2026-10-05',
    endDate: '2026-10-07',
    location: 'Austin Convention Center, Austin, TX',
    audience: 'Developers, product managers, data engineers, and startup founders in the ZipData ecosystem',
    objective: 'Launch ZipData v3 publicly, run live coding workshops, and build community around the new API',
    company: 'ZipData',
    presence: 'Headline sponsor with main stage keynote + 20x20 branded lounge',
    status: 'planning',
    progress: 3,
    coverGradient: 'from-slate-700 to-zinc-900',
    notes: 'Flagship developer conference. Biggest footprint of the year. Main stage keynote slot is 9am Day 1. Branded lounge with furniture and screens.',
    tags: ['developer', 'tech', 'austin', 'keynote', 'launch', 'fall'],
    links: [
      { label: 'BUILD Conference', url: 'https://build.zipdata.io' },
      { label: 'Keynote Prep Portal', url: 'https://build.zipdata.io/speakers' },
    ],
    contacts: [
      { name: 'Alex Kim', role: 'ZipData DevRel Lead', email: 'akim@zipdata.io' },
      { name: 'Jordan Hayes', role: 'Conference Producer', email: 'jhayes@build.zipdata.io' },
      { name: 'Mia Vasquez', role: 'Branding & Design Lead', email: 'mvasquez@zipdata.io' },
    ],
    deadlines: [
      { id: 'dl-b1', title: 'Brand direction locked', date: '2026-08-15', type: 'design', done: false },
      { id: 'dl-b2', title: 'Keynote deck template', date: '2026-09-01', type: 'design', done: false },
      { id: 'dl-b3', title: 'Lounge graphics approved', date: '2026-09-15', type: 'review', done: false },
      { id: 'dl-b4', title: 'All print files submitted', date: '2026-09-20', type: 'print', done: false },
      { id: 'dl-b5', title: 'Shipped to Austin venue', date: '2026-09-28', type: 'shipping', done: false },
      { id: 'dl-b6', title: 'BUILD Conference', date: '2026-10-05', type: 'conference', done: false },
    ],
    assets: [
      {
        id: 'a-b1',
        title: 'Keynote Slide Template',
        type: 'pdf',
        previewColor: 'bg-slate-600',
        aspectRatio: '16/9',
        status: 'pending',
        notes: 'Main stage keynote slide deck template — v3 launch theme',
        tags: ['keynote', 'slides', 'digital'],
        mapPosition: { x: 80, y: 80 },
      },
      {
        id: 'a-b2',
        title: 'Lounge Backdrop — 20ft',
        type: 'banner',
        previewColor: 'bg-zinc-700',
        aspectRatio: '20/8',
        status: 'pending',
        notes: 'Extra-wide branded lounge backdrop',
        tags: ['banner', 'booth', 'print'],
        mapPosition: { x: 350, y: 60 },
      },
      {
        id: 'a-b3',
        title: 'Conference Booth Mockup',
        type: 'mockup',
        previewColor: 'bg-slate-500',
        aspectRatio: '4/3',
        status: 'pending',
        notes: '3D mockup of branded lounge layout',
        tags: ['mockup', 'booth'],
        mapPosition: { x: 700, y: 100 },
      },
      {
        id: 'a-b4',
        title: 'Social — BUILD Announcement',
        type: 'social',
        previewColor: 'bg-zinc-500',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'Twitter/X + LinkedIn headline sponsor announcement',
        tags: ['social', 'digital'],
        mapPosition: { x: 100, y: 350 },
      },
      {
        id: 'a-b5',
        title: 'Landing Page — BUILD 2026',
        type: 'landing',
        previewColor: 'bg-slate-800',
        aspectRatio: '16/9',
        status: 'pending',
        notes: 'Event landing page on zipdata.io/build2026',
        tags: ['digital', 'web', 'landing'],
        mapPosition: { x: 400, y: 400 },
      },
      {
        id: 'a-b6',
        title: 'Conference Tote Bag — Swag',
        type: 'swag',
        previewColor: 'bg-zinc-800',
        aspectRatio: '4/5',
        status: 'pending',
        notes: 'Premium canvas tote for all attendees — 500 qty',
        tags: ['swag', 'giveaway'],
        mapPosition: { x: 700, y: 420 },
      },
      {
        id: 'a-b7',
        title: 'Ad — Sponsor Signage Block',
        type: 'ad',
        previewColor: 'bg-zinc-600',
        aspectRatio: '3/2',
        status: 'pending',
        notes: 'Digital signage ad running on venue screens',
        tags: ['ad', 'digital', 'signage'],
        mapPosition: { x: 950, y: 300 },
      },
      {
        id: 'a-b8',
        title: 'QR Code — v3 API Docs',
        type: 'qr',
        previewColor: 'bg-slate-400',
        aspectRatio: '1/1',
        status: 'pending',
        notes: 'QR to zipdata.io/docs/v3 for workshop attendees',
        tags: ['qr', 'digital'],
        mapPosition: { x: 200, y: 600 },
      },
    ],
  },
];

export const getEventById = (id: string) => events.find((e) => e.id === id);
