import type { CompanyGuideline, Template, DirectoryEntry } from './types';

export const guidelines: CompanyGuideline[] = [
  {
    id: 'prek-club-2026',
    company: 'PreK.Club',
    year: 2026,
    theme: 'Born to Teach',
    tagline: 'Empowering early childhood providers to grow with confidence.',
    color: '#16a34a',
    mission: 'PreK.Club is a child care management platform built for early childhood providers — simplifying enrollment, attendance, payments, and family communication in one place.',
    audience: 'Child care directors, center owners, and early childhood providers looking to grow and modernize their programs.',
    toneDescriptors: ['Energetic', 'Empowering', 'Approachable', 'Solution-focused', 'Warm'],
    toneAvoid: ['Corporate jargon', 'Pushy sales language', 'Overly technical terms', 'Talking down to providers'],
    messages: [
      'PreK.Club simplifies the day-to-day so providers can focus on what matters most — the children.',
      'Modern child care management for growing programs.',
      'Enrollment, attendance, payments, and family communication — all in one place.',
      'We are built by people who understand early childhood, for the people who live it.',
      'Grow with confidence. PreK.Club grows with you.',
    ],
    headlines: {
      primary: 'The Child Care Software to Grow Your Program',
      variations: [
        'Modern Child Care Management for Growing Programs',
        'Simplify Your Program. Grow with Confidence.',
        'Born to Teach. Built to Grow.',
      ],
    },
    ctas: ['Book a Demo', 'Explore PreK.Club', 'Schedule a Walkthrough', 'Scan to Learn More'],
    modes: [
      {
        mode: 'selling',
        label: 'Conference / Selling',
        description:
          'When we are actively present at a conference booth, sponsor table, or sales event. The goal is to generate demos, partnerships, and sign-ups.',
        tone: 'Energetic, confident, solution-focused. Lead with what the provider gains. Make it easy to say yes.',
        headline: 'The Child Care Software to Grow Your Program',
        cta: 'Book a Demo · Explore PreK.Club · Schedule a Walkthrough',
        contexts: ['FACCM & APPLE Conference', 'Smart Start NC', 'Conference Booths'],
        examples: [
          { channel: 'Booth banner', text: 'Modern Child Care Management for Growing Programs. Stop by for a live demo.' },
          { channel: 'Social (pre-event)', text: "We'll be at [Conference Name] — stop by Booth #X to see how PreK.Club helps providers simplify enrollment, attendance, and family communication." },
          { channel: 'Social (during)', text: "Day 1 at #FACCM2026! We're excited to connect with early learning leaders across Florida. Come find us and see PreK.Club in action. 🌴 #PreKClub #EarlyLearning" },
          { channel: 'Postcard', text: 'Enrollment. Attendance. Payments. Family Communication. All in one place. Scan to explore PreK.Club.' },
          { channel: 'Follow-up email', text: "Thanks for connecting with PreK.Club! We'd love to show you how we can simplify your day-to-day. Reply to book a walkthrough at your convenience." },
        ],
      },
      {
        mode: 'gratitude',
        label: 'Appreciation / Non-selling',
        description:
          'When we attend or sponsor events that are NOT about selling — Teacher Planning Week, Champions for Children, appreciation events. The message centers on them, not our product. No CTAs, no product pitches.',
        tone: 'Warm, humble, celebratory. We are a guest in their world. It\'s about them.',
        headline: 'Thank You for Everything You Do',
        cta: '',
        contexts: ['Teacher Planning Week', 'Champions for Children', 'Appreciation Luncheons'],
        examples: [
          { channel: 'Social', text: "Happy Teacher Planning Week! To every early childhood educator preparing for an amazing year — thank you. Your work matters more than you know. 💛 #TeacherPlanningWeek #EarlyChildhood" },
          { channel: 'Social', text: "Today we celebrate the champions behind Champions for Children. Grateful to stand alongside educators who show up every single day for the youngest learners. #ChampionsForChildren" },
          { channel: 'Print / Card', text: 'To the educators who show up every day — thank you. What you do is extraordinary.' },
          { channel: 'Email', text: "We are honored to be part of your community. Today isn't about us — it's about recognizing the incredible work you do for children and families." },
        ],
      },
    ],
  },
  {
    id: 'wels-2026',
    company: 'WELS',
    year: 2026,
    theme: 'Early Learning Data Matters',
    tagline: 'Integrated early learning data systems that help communities make better decisions.',
    color: '#7c3aed',
    mission: 'WELS supports excellence in child development and early learning through comprehensive data systems, automation, analytics, and practical implementation support for early childhood partners.',
    audience: 'Early learning coalitions, Head Start and state administrators, community partners, workforce leaders, providers, family-facing programs, and organizations that need clearer data, workflows, and outcomes.',
    toneDescriptors: ['Purposeful', 'Systems-minded', 'Data-informed', 'Collaborative', 'Practical', 'Community-centered'],
    toneAvoid: ['Dashboard-only software talk', 'Vague workforce buzzwords', 'Overclaiming ownership of partner programs', 'Cold technical language'],
    messages: [
      'Early learning data matters because better information helps communities support children, families, and providers with more clarity.',
      'WELS connects the people, tools, workflows, and insights that early childhood systems need to move forward.',
      'Strong systems help partners see what is working, reduce friction, and improve outcomes across programs and communities.',
      'WELS is at its best when it is a practical partner: data, implementation, automation, reporting, and support.',
      'We support early childhood excellence by helping organizations turn complex information into useful action.',
    ],
    headlines: {
      primary: 'Early Learning Data Matters',
      variations: [
        'Smart Minds Start with Smart Systems',
        'One Goal. Connected Systems. Better Outcomes.',
        'Connecting People, Tools, and Insights',
        'Data • Providers • Workflows • Families',
      ],
    },
    ctas: ['Connect with WELS', 'Learn about WELS', 'Start a conversation', 'Scan to connect with WELS'],
    modes: [
      {
        mode: 'selling',
        label: 'Systems Partner / Lead Generation',
        description:
          'Use when WELS needs to generate conversations with coalitions, Head Start, CSCs, trusts, state administrators, and early childhood systems partners.',
        tone: 'Professional, clear, and outcome-oriented. Speak to the system problem first, then connect data and workflows to the partner goal.',
        headline: 'One Goal. Connected Systems. Better Outcomes.',
        cta: 'Connect with WELS · Start a conversation · Scan to connect with WELS',
        contexts: ['One Goal Summer Conference', 'AELC Conference', 'Annual Leadership Conference', 'MDHS Better Together'],
        examples: [
          { channel: 'Conference ad', text: 'One Goal. Connected Systems. Better Outcomes. DATA • PROVIDERS • WORKFLOWS • FAMILIES.' },
          { channel: 'Booth talking point', text: 'WELS helps early learning partners connect systems, data, and workflows that support providers and families.' },
          { channel: 'Social (pre-event)', text: "We're proud to support [Conference Name] and connect with early childhood leaders working to build smarter, stronger systems for children and families." },
        ],
      },
      {
        mode: 'gratitude',
        label: 'Appreciation / Recognition',
        description:
          'Events or moments where the focus is recognizing educators, directors, and the workforce. We show up as partners and champions of the community, not vendors.',
        tone: 'Respectful, community-oriented. Acknowledge their leadership and dedication. No selling.',
        headline: 'Honoring the Leaders Who Build the Workforce',
        cta: '',
        contexts: ['Champions for Children', 'Director Appreciation', 'Provider Recognition Events', 'Partner recognition'],
        examples: [
          { channel: 'Social', text: 'To the directors, coaches, and administrators shaping the future of early childhood — we see your leadership and we are grateful. #EarlyChildhoodLeadership' },
          { channel: 'Card / Print', text: 'Your leadership strengthens programs and transforms lives. Thank you.' },
          { channel: 'Print / Card', text: 'You care for our children. We provide you with caring solutions.' },
        ],
      },
      {
        mode: 'awareness',
        label: 'Thought Leadership / Awareness',
        description:
          'Use when WELS is not selling a product but reinforcing why early learning data, systems, and collaboration matter.',
        tone: 'Educational, grounded, and generous. Keep it simple enough for non-technical partners but substantial enough for systems leaders.',
        headline: 'Smart Minds Start with Smart Systems',
        cta: 'Learn more · Connect with WELS',
        contexts: ['Smart Start Conference', 'BUILD', 'CFM Summit', 'Partner sponsorships'],
        examples: [
          { channel: 'Sponsor ad', text: 'At WELS Systems Foundation, we believe building smarter communities starts with connecting the right people, tools, and insights.' },
          { channel: 'Social', text: 'Early learning systems work better when data, technology, and collaboration support the people doing the work.' },
          { channel: 'Print', text: 'WELS Systems Foundation is proud to support the impactful work of partners building a brighter future for children.' },
        ],
      },
    ],
  },
  {
    id: 'zipdata-2026',
    company: 'ZipData',
    year: 2026,
    theme: 'Technology Support That Keeps Work Moving',
    tagline: 'IT, cybersecurity, cloud, and support services for organizations that need dependable technology partners.',
    color: '#0ea5e9',
    mission: 'ZipData helps businesses and nonprofits plan, secure, host, support, and improve their technology — from strategy and infrastructure to cloud services, cybersecurity, help desk, and local or remote IT support.',
    audience: 'Small and mid-sized businesses, nonprofits, professional teams, event partners, and organizations that need practical technology guidance without enterprise complexity.',
    toneDescriptors: ['Trustworthy', 'Technical but clear', 'Responsive', 'Practical', 'Security-minded', 'Service-oriented'],
    toneAvoid: ['Fear-based cybersecurity copy', 'Overly complex IT acronyms', 'Generic MSP language', 'Hard-sell urgency', 'Unverified security claims'],
    messages: [
      'ZipData keeps technology practical: strategy, support, security, hosting, cloud, and service in one dependable partner.',
      'When systems are protected and supported, teams can focus on the work they came to do.',
      'Good IT support should feel clear, responsive, and close to the organization.',
      'Cybersecurity messaging should build trust and readiness, not fear.',
      'ZipData works best when the message is specific: what problem is solved, who gets support, and how they can start a conversation.',
    ],
    headlines: {
      primary: 'Technology Support That Keeps Work Moving',
      variations: [
        'Secure. Supported. Ready for What Comes Next.',
        'Practical IT Support for Growing Organizations',
        'Cybersecurity, Cloud, and Help Desk Support in One Place',
        'Technology Strategy Without the Noise',
      ],
    },
    ctas: ['Connect with ZipData', 'Request IT support', 'Learn more', 'Schedule a consultation'],
    modes: [
      {
        mode: 'selling',
        label: 'Business / Lead Generation',
        description:
          'Use for landing pages, QR campaigns, and events where ZipData is actively collecting qualified IT, cybersecurity, cloud, or support leads.',
        tone: 'Direct, practical, and trust-building. Focus on the problem the buyer recognizes and the support ZipData can provide.',
        headline: 'Secure. Supported. Ready for What Comes Next.',
        cta: 'Connect with ZipData · Schedule a consultation · Learn more',
        contexts: ['FACE Cuba', 'Business luncheons', 'Cybersecurity outreach', 'Professional services leads', 'AELC Conference'],
        examples: [
          { channel: 'Landing hero', text: 'Protect your business with practical cybersecurity and IT support from ZipData.' },
          { channel: 'QR CTA', text: 'Scan to connect with ZipData and learn how your organization can strengthen its technology support.' },
          { channel: 'Follow-up email', text: 'Thanks for connecting with ZipData. Our team can help review your IT support, cybersecurity, cloud, or help desk needs.' },
          { channel: 'AELC talking point', text: "Real ELC experiences with security breaches show why data protection and cybersecurity readiness matter — ZipData helps organizations strengthen practices before they're tested." },
        ],
      },
      {
        mode: 'awareness',
        label: 'Trust / Technology Education',
        description:
          'Use when the goal is to teach, build confidence, or position ZipData as a practical guide before asking for a lead.',
        tone: 'Helpful and plain-spoken. Explain the risk or opportunity without making the audience feel behind.',
        headline: 'Technology Strategy Without the Noise',
        cta: 'Learn more · Connect with ZipData',
        contexts: ['Educational posts', 'Partner newsletters', 'Nonprofit technology outreach'],
        examples: [
          { channel: 'Social', text: 'Technology should support your team, not slow it down. ZipData helps organizations make IT, cloud, and security decisions with more clarity.' },
          { channel: 'Newsletter', text: 'From help desk support to cybersecurity planning, a dependable IT partner can help your organization stay ready for the work ahead.' },
        ],
      },
    ],
  },
  {
    id: 'bwelz-2026',
    company: 'BWELZ',
    year: 2026,
    theme: 'Caring Solutions',
    tagline: 'Bluejeanware + WELS + ZipData, together as BWELZ.',
    color: '#0369a1',
    mission: 'BWELZ is an employee-owned family of caring solutions that brings together Bluejeanware, WELS, and ZipData — combining technology, data, implementation, and service for organizations that support children, families, and communities.',
    audience: 'Early childhood systems, nonprofits, child and family-serving organizations, provider networks, workforce partners, and the internal teams who carry the BWELZ mission forward.',
    toneDescriptors: ['Human', 'Purpose-led', 'Employee-owned', 'Practical', 'Warm', 'Future-facing'],
    toneAvoid: ['Cold SaaS language', 'Generic network claims', 'Overexplaining the merger', 'Corporate hype', 'Pressure or urgency tactics'],
    messages: [
      'Bluejeanware + WELS + ZipData = BWELZ.',
      'BWELZ is the shared home for caring solutions built from service, technology, data, and real community work.',
      'Our journey brings together people, systems, and data so organizations can care for children and families with more clarity.',
      'You care for our children. We provide you with caring solutions.',
      'Employee-owned means the people doing the work are invested in the people we serve.',
    ],
    headlines: {
      primary: 'Caring Solutions for the People Who Care',
      variations: [
        'Bluejeanware + WELS + ZipData = BWELZ',
        'Our Journey. Our Future. Caring Solutions.',
        'Built From Service. Connected by Care.',
      ],
    },
    ctas: ['Learn more', 'Explore BWELZ', 'Connect with us', 'Discover caring solutions'],
    modes: [
      {
        mode: 'awareness',
        label: 'Brand Introduction / Awareness',
        description:
          'Use this when the audience needs to understand what BWELZ is and how Bluejeanware, WELS, and ZipData fit together. Lead with story and purpose, then make the equation simple.',
        tone: 'Warm, clear, identity-building. Make the transition feel like a natural evolution, not a corporate announcement.',
        headline: 'Bluejeanware + WELS + ZipData = BWELZ',
        cta: 'Learn more · Explore BWELZ',
        contexts: ['Launch materials', 'Partner events', 'Conference QR cards', 'About BWELZ moments'],
        examples: [
          { channel: 'Print / QR', text: 'bwelz is our journey, this is our future.' },
          { channel: 'Social', text: 'Bluejeanware + WELS + ZipData are coming together as BWELZ: caring solutions built from technology, data, and service.' },
          { channel: 'Booth', text: 'Caring solutions for the people and organizations who care for children and families.' },
        ],
      },
      {
        mode: 'gratitude',
        label: 'Recognition / Community Gratitude',
        description:
          'For Champions for Children, partner recognition, and mission-centered events where BWELZ is present as a supporter. The focus stays on honorees, educators, children, and community partners.',
        tone: 'Humble, celebratory, human. Let the audience feel seen before BWELZ is seen.',
        headline: 'Thank You',
        cta: '',
        contexts: ['Champions for Children', 'Demoya Foundation events', 'Partner appreciation', 'Community recognition'],
        examples: [
          { channel: 'Print / Card', text: 'You care for our children. We provide you with caring solutions.' },
          { channel: 'Social', text: 'Thank you to the people and partners who keep showing up for children, families, and the communities around them.' },
          { channel: 'Event creative', text: 'Made with love in Miami.' },
        ],
      },
      {
        mode: 'launch',
        label: 'Launch / Future-facing',
        description:
          'For moments that explain the next chapter of BWELZ. Use when the message is about where the company is going, the employee-owned identity, or the future of its connected solutions.',
        tone: 'Optimistic, grounded, and personal. Big feeling is allowed, but anchor it in service.',
        headline: 'Our Journey. Our Future. Caring Solutions.',
        cta: 'Learn more · Connect with us',
        contexts: ['Company announcement', 'Internal-facing materials', 'Future-state creative'],
        examples: [
          { channel: 'Poster', text: 'Coming in 2024!' },
          { channel: 'Announcement', text: 'BWELZ brings together the people, platforms, and purpose behind Bluejeanware, WELS, and ZipData.' },
          { channel: 'Website blurb', text: 'Employee-owned, service-driven, and built for organizations that care.' },
        ],
      },
    ],
  },
];

export const templates: Template[] = [
  {
    id: 'tmpl-postcard-prek',
    title: 'PreK.Club — What Is PreK.Club? Postcard',
    type: 'postcard',
    company: 'PreK.Club',
    description: '4×6 postcard. Front: brand value prop. Back: QR + contact. Used at conference tables.',
    externalUrl: '',
    tags: ['postcard', 'print', '4x6', 'conference'],
    lastUpdated: '2026-05-01',
  },
  {
    id: 'tmpl-backdrop-prek',
    title: 'PreK.Club — Born to Teach Backdrop',
    type: 'banner',
    company: 'PreK.Club',
    description: '8×8 ft printed backdrop for conference photography. High-res export for print production.',
    externalUrl: '',
    tags: ['backdrop', 'print', 'booth', '8x8', 'born-to-teach'],
    lastUpdated: '2026-04-15',
  },
  {
    id: 'tmpl-tablecloth-prek',
    title: 'PreK.Club — 6ft Tablecloth',
    type: 'tablecloth',
    company: 'PreK.Club',
    description: '6ft table throw. PreK.Club brand green. Reusable across all conference appearances.',
    externalUrl: '',
    tags: ['tablecloth', 'print', 'booth', '6ft'],
    lastUpdated: '2026-03-10',
  },
  {
    id: 'tmpl-email-followup',
    title: 'Post-Conference Follow-Up Email',
    type: 'email',
    company: 'PreK.Club',
    description: 'Standard follow-up email sent to leads collected at booth. Includes demo CTA and resource links.',
    externalUrl: '',
    tags: ['email', 'follow-up', 'conference', 'lead'],
    lastUpdated: '2026-04-20',
  },
  {
    id: 'tmpl-social-preEvent',
    title: 'Social — Pre-Event Post Template',
    type: 'copy',
    description: 'Reusable copy template for announcing presence at upcoming conferences. Works for all companies with variable fill-ins.',
    externalUrl: '',
    tags: ['social', 'copy', 'pre-event', 'template'],
    lastUpdated: '2026-04-01',
  },
  {
    id: 'tmpl-social-gratitude',
    title: 'Social — Gratitude / Appreciation Template',
    type: 'copy',
    description: 'Copy template for appreciation contexts (Teacher Planning Week, Champions for Children). No product CTAs.',
    externalUrl: '',
    tags: ['social', 'copy', 'gratitude', 'appreciation', 'template'],
    lastUpdated: '2026-04-01',
  },
];

export const directory: DirectoryEntry[] = [
  {
    id: 'dir-anything-display',
    name: 'Mark B',
    company: 'Anything Display',
    type: 'vendor',
    role: 'Large-format display & print production',
    services: ['Backdrops', 'Step & repeat', 'Large-format banners', 'Display hardware'],
    email: 'mark@anythingdisplay.com',
    phone: '239-433-9738',
    website: 'https://www.anythingdisplay.com',
    notes: 'Vendor for Born to Teach 8×8 backdrop. SO-1117613, PO#57195. Delivered May 1.',
    tags: ['print', 'backdrop', 'large-format', 'display'],
  },
  {
    id: 'dir-postcard-printer',
    name: 'Postcard Printer',
    company: '',
    type: 'vendor',
    role: 'Offset and digital short-run print',
    services: ['Postcards', 'Flyers', 'Brochures'],
    email: '',
    phone: '',
    website: '',
    notes: 'Used for PreK.Club 4×6 postcards. Add vendor name, contact, and turnaround time.',
    tags: ['print', 'postcard', 'short-run'],
  },
  {
    id: 'dir-tablecloth-vendor',
    name: 'Tablecloth / Swag Vendor',
    company: '',
    type: 'vendor',
    role: 'Branded promotional products and table throws',
    services: ['Tablecloths', 'Tote bags', 'Swag items'],
    email: '',
    phone: '',
    website: '',
    notes: 'Source for 6ft tablecloth and canvas totes. Add vendor details.',
    tags: ['swag', 'tablecloth', 'promo'],
  },
  {
    id: 'dir-wels-account',
    name: 'James Thornton',
    company: 'WELS',
    type: 'internal',
    role: 'WELS Account Manager',
    services: [],
    email: 'jthornton@wels.com',
    tags: ['wels', 'account', 'internal'],
  },
  {
    id: 'dir-prek-partner',
    name: 'Oscar Reeves',
    company: 'PreK.Club',
    type: 'internal',
    role: 'PreK.Club Partner Lead',
    services: [],
    email: 'oreeves@prek.club',
    tags: ['prek.club', 'partner', 'internal'],
  },
  {
    id: 'dir-del-mathew',
    name: 'Mathew',
    company: 'DEL',
    type: 'partner',
    role: 'CLASS Cycle Notes Session Lead',
    services: [],
    email: '',
    phone: '',
    website: '',
    notes: 'Met at One Goal Summer Conference 2026. Clarified DEL expectations for CLASS cycle notes and summaries — objective, indicator-tallied bullet points, not narrative prose.',
    tags: ['del', 'class', 'one-goal', 'wels'],
  },
  {
    id: 'dir-molly-grant',
    name: 'Molly Grant',
    company: 'AELC',
    type: 'partner',
    role: 'AELC Collaborative Showcase Lead',
    services: [],
    email: '',
    phone: '',
    website: '',
    notes: 'Excited to showcase ZipData at the upcoming AELC Conference as a collaborative effort with ELC partners on data and cybersecurity. See aelc-2026 event.',
    tags: ['aelc', 'zipdata', 'cybersecurity', 'partner'],
  },
  {
    id: 'dir-fred-tampa',
    name: 'Fred',
    company: 'Tampa',
    type: 'partner',
    role: 'Former Partner',
    services: [],
    email: '',
    phone: '',
    website: '',
    notes: 'Reconnected at One Goal Summer Conference 2026. Doing great work in Tampa; former partner turned long-term contact.',
    tags: ['one-goal', 'tampa', 'former-partner'],
  },
  {
    id: 'dir-dana',
    name: 'Dana',
    company: '',
    type: 'contact',
    role: 'Account Holder',
    services: [],
    email: '',
    phone: '',
    website: '',
    notes: 'Met at One Goal Summer Conference 2026. Ives resolved a technical issue for her on the spot at the booth.',
    tags: ['one-goal', 'account-holder'],
  },
  {
    id: 'dir-ives',
    name: 'Ives',
    company: '',
    type: 'internal',
    role: 'Technical Support',
    services: ['On-site technical troubleshooting'],
    email: '',
    phone: '',
    website: '',
    notes: 'Resolved a technical issue for Dana on the spot at One Goal Summer Conference 2026 — example of the value of in-person support.',
    tags: ['internal', 'support', 'one-goal'],
  },
  {
    id: 'dir-miami-pikitin',
    name: 'Pikitin',
    company: 'Miami',
    type: 'partner',
    role: 'Trainer',
    services: ['Educator training'],
    email: '',
    phone: '',
    website: '',
    notes: 'Miami trainer, visited One Goal Summer Conference 2026 booth. Flagged ElevatEd portal responsiveness issues on subsidized phones and missed training notifications.',
    tags: ['miami', 'trainer', 'one-goal', 'elevated'],
  },
  {
    id: 'dir-miami-discovery-source',
    name: 'Discovery Source',
    company: 'Miami',
    type: 'partner',
    role: 'Trainer',
    services: ['Educator training'],
    email: '',
    phone: '',
    website: '',
    notes: 'Miami trainer, visited One Goal Summer Conference 2026 booth. Same feedback as Pikitin on ElevatEd portal and training notifications.',
    tags: ['miami', 'trainer', 'one-goal', 'elevated'],
  },
];
