import type { CompanyGuideline, Template, DirectoryEntry } from './types';

export const guidelines: CompanyGuideline[] = [
  {
    id: 'prek-club-2026',
    company: 'PreK.Club',
    year: 2026,
    theme: 'Born to Teach',
    tagline: 'Empowering early childhood providers to grow with confidence.',
    color: '#16a34a',
    mission: 'PreK.Club is a child care management platform built for early childhood providers — simplifying enrollment, attendance, payments, and family communication in one place.',
    audience: 'Child care directors, center owners, and early childhood providers looking to grow and modernize their programs.',
    toneDescriptors: ['Energetic', 'Empowering', 'Approachable', 'Solution-focused', 'Warm'],
    toneAvoid: ['Corporate jargon', 'Pushy sales language', 'Overly technical terms', 'Talking down to providers'],
    messages: [
      'PreK.Club simplifies the day-to-day so providers can focus on what matters most — the children.',
      'Modern child care management for growing programs.',
      'Enrollment, attendance, payments, and family communication — all in one place.',
      'We are built by people who understand early childhood, for the people who live it.',
      'Grow with confidence. PreK.Club grows with you.',
    ],
    headlines: {
      primary: 'The Child Care Software to Grow Your Program',
      variations: [
        'Modern Child Care Management for Growing Programs',
        'Simplify Your Program. Grow with Confidence.',
        'Born to Teach. Built to Grow.',
      ],
    },
    ctas: ['Book a Demo', 'Explore PreK.Club', 'Schedule a Walkthrough', 'Scan to Learn More'],
    modes: [
      {
        mode: 'selling',
        label: 'Conference / Selling',
        description:
          'When we are actively present at a conference booth, sponsor table, or sales event. The goal is to generate demos, partnerships, and sign-ups.',
        tone: 'Energetic, confident, solution-focused. Lead with what the provider gains. Make it easy to say yes.',
        headline: 'The Child Care Software to Grow Your Program',
        cta: 'Book a Demo · Explore PreK.Club · Schedule a Walkthrough',
        contexts: ['FACCM & APPLE Conference', 'Smart Start NC', 'Conference Booths'],
        examples: [
          { channel: 'Booth banner', text: 'Modern Child Care Management for Growing Programs. Stop by for a live demo.' },
          { channel: 'Social (pre-event)', text: "We'll be at [Conference Name] — stop by Booth #X to see how PreK.Club helps providers simplify enrollment, attendance, and family communication." },
          { channel: 'Social (during)', text: "Day 1 at #FACCM2026! We're excited to connect with early learning leaders across Florida. Come find us and see PreK.Club in action. 🌴 #PreKClub #EarlyLearning" },
          { channel: 'Postcard', text: 'Enrollment. Attendance. Payments. Family Communication. All in one place. Scan to explore PreK.Club.' },
          { channel: 'Follow-up email', text: "Thanks for connecting with PreK.Club! We'd love to show you how we can simplify your day-to-day. Reply to book a walkthrough at your convenience." },
        ],
      },
      {
        mode: 'gratitude',
        label: 'Appreciation / Non-selling',
        description:
          'When we attend or sponsor events that are NOT about selling — Teacher Planning Week, Champions for Children, appreciation events. The message centers on them, not our product. No CTAs, no product pitches.',
        tone: 'Warm, humble, celebratory. We are a guest in their world. It\'s about them.',
        headline: 'Thank You for Everything You Do',
        cta: '',
        contexts: ['Teacher Planning Week', 'Champions for Children', 'Appreciation Luncheons'],
        examples: [
          { channel: 'Social', text: "Happy Teacher Planning Week! To every early childhood educator preparing for an amazing year — thank you. Your work matters more than you know. 💛 #TeacherPlanningWeek #EarlyChildhood" },
          { channel: 'Social', text: "Today we celebrate the champions behind Champions for Children. Grateful to stand alongside educators who show up every single day for the youngest learners. #ChampionsForChildren" },
          { channel: 'Print / Card', text: 'To the educators who show up every day — thank you. What you do is extraordinary.' },
          { channel: 'Email', text: "We are honored to be part of your community. Today isn't about us — it's about recognizing the incredible work you do for children and families." },
        ],
      },
    ],
  },
  {
    id: 'wels-2026',
    company: 'WELS',
    year: 2026,
    theme: 'Grow. Lead. Succeed.',
    tagline: 'Workforce solutions for a stronger early childhood ecosystem.',
    color: '#7c3aed',
    mission: 'WELS provides workforce development solutions for early childhood programs — supporting directors, educators, and administrators with the tools and training they need to build stronger teams.',
    audience: 'Early childhood program directors, administrators, and workforce development professionals.',
    toneDescriptors: ['Professional', 'Authoritative', 'Forward-looking', 'Empowering', 'Community-driven'],
    toneAvoid: ['Overly casual', 'Vague claims', 'Generic workforce buzzwords without substance'],
    messages: [
      'Grow. Lead. Succeed. — the theme that defines our 2026 focus.',
      'WELS equips directors and educators with the tools to build stronger programs.',
      'Workforce development is the foundation of quality early childhood education.',
      'We connect people, programs, and opportunities across the early childhood ecosystem.',
      'Leadership is learned. We are here to help you lead.',
    ],
    headlines: {
      primary: 'Workforce Solutions Built for Early Childhood Leaders',
      variations: [
        'Empowering Directors. Strengthening Programs.',
        'Building the Workforce of Tomorrow.',
        'Grow. Lead. Succeed. — WELS 2026',
      ],
    },
    ctas: ['Connect with our team', 'Learn about WELS', 'Schedule a consultation'],
    modes: [
      {
        mode: 'selling',
        label: 'Conference / Sponsorship',
        description:
          'Active sponsorship presence at professional development conferences. Goal is to establish WELS credibility, generate leads, and connect with decision-makers.',
        tone: 'Professional, authoritative, forward-looking. Speak to administrators and directors. Show value, not features.',
        headline: 'Workforce Solutions Built for Early Childhood Leaders',
        cta: 'Connect with our team · Learn about WELS · Schedule a consultation',
        contexts: ['Grow Lead Succeed 2026', 'FACCM', 'APPLE Accreditation'],
        examples: [
          { channel: 'Booth signage', text: 'Empowering directors. Strengthening programs. Building the workforce of tomorrow.' },
          { channel: 'Social (pre-event)', text: "Excited to be at #GrowLeadSucceed2026! We're connecting with early childhood leaders who are ready to build stronger teams. Find us at [location]. #WELS #EarlyChildhoodWorkforce" },
          { channel: 'Social (during)', text: 'Amazing conversations on Day 1. Talking workforce development, leadership, and what it takes to run a thriving early childhood program. #GrowLeadSucceed #WELS' },
        ],
      },
      {
        mode: 'gratitude',
        label: 'Appreciation / Recognition',
        description:
          'Events or moments where the focus is recognizing educators, directors, and the workforce. We show up as partners and champions of the community, not vendors.',
        tone: 'Respectful, community-oriented. Acknowledge their leadership and dedication. No selling.',
        headline: 'Honoring the Leaders Who Build the Workforce',
        cta: '',
        contexts: ['Director Appreciation', 'Provider Recognition Events'],
        examples: [
          { channel: 'Social', text: 'To the directors, coaches, and administrators shaping the future of early childhood — we see your leadership and we are grateful. #EarlyChildhoodLeadership' },
          { channel: 'Card / Print', text: 'Your leadership strengthens programs and transforms lives. Thank you.' },
        ],
      },
    ],
  },
  {
    id: 'bwelz-2026',
    company: 'BWELZ',
    year: 2026,
    theme: 'Building Networks',
    tagline: 'Connecting providers across the BWELZ national network.',
    color: '#0369a1',
    mission: 'BWELZ builds and sustains a national network of early childhood providers — connecting programs, resources, and opportunities across communities.',
    audience: 'Child care providers, early childhood programs, and organizations looking to connect with a national network.',
    toneDescriptors: ['Inclusive', 'Inviting', 'Community-driven', 'Supportive', 'Optimistic'],
    toneAvoid: ['Transactional language', 'Exclusionary messaging', 'Pressure or urgency tactics'],
    messages: [
      'You are not alone. BWELZ connects providers, resources, and opportunities — nationwide.',
      'Building better childcare starts with community.',
      'Stronger together. The BWELZ network grows when we share, learn, and support each other.',
      'Every program matters. Every provider deserves connection.',
    ],
    headlines: {
      primary: 'Stronger Together. Join the BWELZ Network.',
      variations: [
        'Connected. Supported. Growing.',
        'Building Networks. Building Community.',
      ],
    },
    ctas: ['Learn more', 'Connect with your network', 'Join BWELZ'],
    modes: [
      {
        mode: 'awareness',
        label: 'Network Building / Awareness',
        description:
          'BWELZ events focus on growing the network, awareness among providers, and establishing presence. Less transactional — more relationship-first.',
        tone: 'Inclusive, inviting, community-driven. "Join us" energy. Make people feel welcome.',
        headline: 'Stronger Together. Join the BWELZ Network.',
        cta: 'Learn more · Connect with your network',
        contexts: ['BWELZ National Network Events', 'Regional Meetups'],
        examples: [
          { channel: 'Social', text: 'Building better childcare starts with community. Learn how the BWELZ network supports providers across the country. #BWELZ #ChildCareNetwork' },
          { channel: 'Booth', text: 'You are not alone. BWELZ connects providers, resources, and opportunities — nationwide.' },
        ],
      },
    ],
  },
];

export const templates: Template[] = [
  {
    id: 'tmpl-postcard-prek',
    title: 'PreK.Club — What Is PreK.Club? Postcard',
    type: 'postcard',
    company: 'PreK.Club',
    description: '4×6 postcard. Front: brand value prop. Back: QR + contact. Used at conference tables.',
    externalUrl: '',
    tags: ['postcard', 'print', '4x6', 'conference'],
    lastUpdated: '2026-05-01',
  },
  {
    id: 'tmpl-backdrop-prek',
    title: 'PreK.Club — Born to Teach Backdrop',
    type: 'banner',
    company: 'PreK.Club',
    description: '8×8 ft printed backdrop for conference photography. High-res export for print production.',
    externalUrl: '',
    tags: ['backdrop', 'print', 'booth', '8x8', 'born-to-teach'],
    lastUpdated: '2026-04-15',
  },
  {
    id: 'tmpl-tablecloth-prek',
    title: 'PreK.Club — 6ft Tablecloth',
    type: 'tablecloth',
    company: 'PreK.Club',
    description: '6ft table throw. PreK.Club brand green. Reusable across all conference appearances.',
    externalUrl: '',
    tags: ['tablecloth', 'print', 'booth', '6ft'],
    lastUpdated: '2026-03-10',
  },
  {
    id: 'tmpl-email-followup',
    title: 'Post-Conference Follow-Up Email',
    type: 'email',
    company: 'PreK.Club',
    description: 'Standard follow-up email sent to leads collected at booth. Includes demo CTA and resource links.',
    externalUrl: '',
    tags: ['email', 'follow-up', 'conference', 'lead'],
    lastUpdated: '2026-04-20',
  },
  {
    id: 'tmpl-social-preEvent',
    title: 'Social — Pre-Event Post Template',
    type: 'copy',
    description: 'Reusable copy template for announcing presence at upcoming conferences. Works for all companies with variable fill-ins.',
    externalUrl: '',
    tags: ['social', 'copy', 'pre-event', 'template'],
    lastUpdated: '2026-04-01',
  },
  {
    id: 'tmpl-social-gratitude',
    title: 'Social — Gratitude / Appreciation Template',
    type: 'copy',
    description: 'Copy template for appreciation contexts (Teacher Planning Week, Champions for Children). No product CTAs.',
    externalUrl: '',
    tags: ['social', 'copy', 'gratitude', 'appreciation', 'template'],
    lastUpdated: '2026-04-01',
  },
];

export const directory: DirectoryEntry[] = [
  {
    id: 'dir-anything-display',
    name: 'Mark B',
    company: 'Anything Display',
    type: 'vendor',
    role: 'Large-format display & print production',
    services: ['Backdrops', 'Step & repeat', 'Large-format banners', 'Display hardware'],
    email: 'mark@anythingdisplay.com',
    phone: '239-433-9738',
    website: 'https://www.anythingdisplay.com',
    notes: 'Vendor for Born to Teach 8×8 backdrop. SO-1117613, PO#57195. Delivered May 1.',
    tags: ['print', 'backdrop', 'large-format', 'display'],
  },
  {
    id: 'dir-postcard-printer',
    name: 'Postcard Printer',
    company: '',
    type: 'vendor',
    role: 'Offset and digital short-run print',
    services: ['Postcards', 'Flyers', 'Brochures'],
    email: '',
    phone: '',
    website: '',
    notes: 'Used for PreK.Club 4×6 postcards. Add vendor name, contact, and turnaround time.',
    tags: ['print', 'postcard', 'short-run'],
  },
  {
    id: 'dir-tablecloth-vendor',
    name: 'Tablecloth / Swag Vendor',
    company: '',
    type: 'vendor',
    role: 'Branded promotional products and table throws',
    services: ['Tablecloths', 'Tote bags', 'Swag items'],
    email: '',
    phone: '',
    website: '',
    notes: 'Source for 6ft tablecloth and canvas totes. Add vendor details.',
    tags: ['swag', 'tablecloth', 'promo'],
  },
  {
    id: 'dir-wels-account',
    name: 'James Thornton',
    company: 'WELS',
    type: 'internal',
    role: 'WELS Account Manager',
    services: [],
    email: 'jthornton@wels.com',
    tags: ['wels', 'account', 'internal'],
  },
  {
    id: 'dir-prek-partner',
    name: 'Oscar Reeves',
    company: 'PreK.Club',
    type: 'internal',
    role: 'PreK.Club Partner Lead',
    services: [],
    email: 'oreeves@prek.club',
    tags: ['prek.club', 'partner', 'internal'],
  },
];
